package de.atlasmc.node.event.inventory;

public enum InventoryButtonType {

	ENCHANTING_TOP_ENCHANTMENT,
	ENCHANTING_MIDDLE_ENCHANTMENT,
	ENCHANTING_BOTTOM_EMCHANTMENT,
	LECTERN_PREVIOUS_PAGE,
	LECTERN_NEXT_PAGE,
	LECTERN_TAKE_BOOK,
	LECTERN_OPEN_PAGE_NUMBER,
	STONECUTTER_RECIPE_NUMBER,
	LOOM_RECIPE_NUMBER;
}
