package de.atlasmc.world;

public enum WorldFlag {
	// BlockFlags
	DISABLE_BLOCKPHYSICS,
	DISABLE_BLOCKFADE, 
	DISABLE_LEAVEDECAY, 
	DISABLE_BLOCKPLACE, 
	DISABLE_BLOCKBREAK,
	DISABLE_LIQUIDFLOW,
	// EntityFlags
	DISABLE_MOBSPAWN, 
	DISABLE_DAMAGE_BY_PLAYER, 
	DISABLE_DAMAGE_TO_ENTITY, 
	DISABLE_DAMAGE_BY_ENTITY,
	DISABLE_DAMAGE_BY_FALL, 
	DISABLE_DAMAGE_BY_BLOCK, 
	DISABLE_DAMAGE_BY_DROWNING, 
	DISABLE_DAMAGE_BY_FIRE, 
	DISABLE_HUNGER;
}
