package de.atlascore.system.init;

import static de.atlasmc.entity.EntityType.*;

import de.atlascore.entity.*;
import de.atlasmc.NamespacedKey;
import de.atlasmc.entity.EntityType;

public class EntityTypeLoader {
	
	public static void loadEntityTypes() {
		AREA_EFFECT_CLOUD = new EntityType(NamespacedKey.MINECRAFT, "AREA_EFFECT_CLOUD", CoreAreaEffectCloud.class);
		ARMOR_STAND = new EntityType(NamespacedKey.MINECRAFT, "ArmorStand", CoreArmorStand.class);
		ARROW = new EntityType(NamespacedKey.MINECRAFT, "ARROW", CoreArrow.class);
		BAT = new EntityType(NamespacedKey.MINECRAFT, "BAT", CoreBat.class); 
		BEE = new EntityType(NamespacedKey.MINECRAFT, "BEE", CoreBee.class);
		BLAZE = new EntityType(NamespacedKey.MINECRAFT, "BLAZE", CoreBlaze.class);
		BOAT = new EntityType(NamespacedKey.MINECRAFT, "BOAT", CoreBoat.class);
		CAT = new EntityType(NamespacedKey.MINECRAFT, "CAT", CoreCow.class);
		CAVE_SPIDER = new EntityType(NamespacedKey.MINECRAFT, "CAVE_SPIDER", CoreCaveSpider.class);
		CHICKEN = new EntityType(NamespacedKey.MINECRAFT, "CHICKEN", CoreChicken.class);
		COD = new EntityType(NamespacedKey.MINECRAFT, "COD", CoreCod.class);
		COW = new EntityType(NamespacedKey.MINECRAFT, "COW", CoreCow.class);
		CREEPER = new EntityType(NamespacedKey.MINECRAFT, "CREEPER", CoreCreeper.class);
		DOLPHIN = new EntityType(NamespacedKey.MINECRAFT, "DOLPHIN", CoreDolphin.class);
		DONKEY = new EntityType(NamespacedKey.MINECRAFT, "DONKEY", CoreDonkey.class);
		DRAGON_FIREBALL = new EntityType(NamespacedKey.MINECRAFT, "DRAGON_FIREBALL", CoreDragonFireball.class);
		DROWNED = new EntityType(NamespacedKey.MINECRAFT, "DROWNED", CoreDrowned.class);
		ELDER_GUARDIAN = new EntityType(NamespacedKey.MINECRAFT, "ELDER_GUARDIAN", CoreElderGuardian.class);
		END_CRYSTAL = new EntityType(NamespacedKey.MINECRAFT, "END_CRYSTAL", CoreEndCrystal.class);
		ENDER_DRAGON = new EntityType(NamespacedKey.MINECRAFT, "ENDER_DRAGON", CoreEnderDragon.class);
		ENDERMAN = new EntityType(NamespacedKey.MINECRAFT, "ENDERMAN", CoreEnderman.class);
		ENDERMITE = new EntityType(NamespacedKey.MINECRAFT, "ENDERMITE", CoreEndermite.class);
		EVOKER = new EntityType(NamespacedKey.MINECRAFT, "EVOKER", CoreEvoker.class);
		EVOKER_FANGS = new EntityType(NamespacedKey.MINECRAFT, "EVOKER_FANGS", CoreEvokerFangs.class);
		EXPERIENCE_ORB = new EntityType(NamespacedKey.MINECRAFT, "EXPERIENCE_ORB", CoreExperienceOrb.class);
		EYE_OF_ENDER = new EntityType(NamespacedKey.MINECRAFT, "EYE_OF_ENDER", CoreEyeOfEnder.class);
		FALLING_BLOCK = new EntityType(NamespacedKey.MINECRAFT, "FALLING_BLOCK", CoreFallingBlock.class);
		FIREWORK_ROCKET = new EntityType(NamespacedKey.MINECRAFT, "FIREWORK_ROCKET", CoreFireworkRocket.class);
		FOX = new EntityType(NamespacedKey.MINECRAFT, "FOX", CoreFox.class);
		GHAST = new EntityType(NamespacedKey.MINECRAFT, "GHAST", CoreGhast.class);
		GIANT = new EntityType(NamespacedKey.MINECRAFT, "GIANT", CoreGiant.class);
		GUARDIAN = new EntityType(NamespacedKey.MINECRAFT, "GUARDIAN", CoreGuardian.class);
		HORSE = new EntityType(NamespacedKey.MINECRAFT, "HORSE", CoreHorse.class);
		HOGLIN = new EntityType(NamespacedKey.MINECRAFT, "HOGLIN", CoreHoglin.class);
		HUSK = new EntityType(NamespacedKey.MINECRAFT, "HUSK", CoreHusk.class);
		ILLUSIONER = new EntityType(NamespacedKey.MINECRAFT, "ILLUSIONER", CoreIllusioner.class);
		IRON_GOLEM = new EntityType(NamespacedKey.MINECRAFT, "IRON_GOLEM", CoreIronGolem.class);
		ITEM = new EntityType(NamespacedKey.MINECRAFT, "ITEM", CoreItem.class);
		ITEM_FRAME = new EntityType(NamespacedKey.MINECRAFT, "ITEM_FRAME", CoreItemFrame.class);
		FIREBALL = new EntityType(NamespacedKey.MINECRAFT, "FIREBALL", CoreLargeFireball.class);
		LEASH_KNOT = new EntityType(NamespacedKey.MINECRAFT, "LEASH_KNOT", CoreLeashKnot.class);
		LIGHTNING_BOLT = new EntityType(NamespacedKey.MINECRAFT, "LIGHTNING_BOLT", CoreLightningBolt.class);
		LLAMA = new EntityType(NamespacedKey.MINECRAFT, "LLAMA", CoreLlama.class);
		LLAMA_SPIT = new EntityType(NamespacedKey.MINECRAFT, "LLAMA_SPIT", CoreLlamaSpit.class);
		MAGMA_CUBE = new EntityType(NamespacedKey.MINECRAFT, "MAGMA_CUBE", CoreMagmaCube.class);
		MINECART = new EntityType(NamespacedKey.MINECRAFT, "MINECART", CoreMinecart.class);
		CHEST_MINECART = new EntityType(NamespacedKey.MINECRAFT, "CHEST_MINECART", CoreMinecartChest.class);
		COMMAND_BLOCK_MINECART = new EntityType(NamespacedKey.MINECRAFT, "COMMAND_BLOCK_MINECART", CoreMinecartCommandBlock.class);
		FURNACE_MINECART = new EntityType(NamespacedKey.MINECRAFT, "FURNACE_MINECART", CoreMinecraftFurnace.class);
		HOPPER_MINECART = new EntityType(NamespacedKey.MINECRAFT, "HOPPER_MINECART", CoreMinecartHopper.class);
		SPAWNER_MINECART = new EntityType(NamespacedKey.MINECRAFT, "SPAWNER_MINECART", CoreMinecartSpawner.class);
		TNT_MINECART = new EntityType(NamespacedKey.MINECRAFT, "TNT_MINECART", CoreMinecartTNT.class);
		MULE = new EntityType(NamespacedKey.MINECRAFT, "MULE", CoreMule.class);
		MOOSHROOM = new EntityType(NamespacedKey.MINECRAFT, "MOOSHROOM", CoreMooshroom.class);
		OCELOT = new EntityType(NamespacedKey.MINECRAFT, "OCELOT", CoreOcelot.class);
		PAINTING = new EntityType(NamespacedKey.MINECRAFT, "PAINTING", CorePainting.class);
		PANDA = new EntityType(NamespacedKey.MINECRAFT, "PANDA", CorePanda.class);
		PARROT = new EntityType(NamespacedKey.MINECRAFT, "PARROT", CoreParrot.class);
		PHANTOM = new EntityType(NamespacedKey.MINECRAFT, "PHANTOM", CorePhantom.class);
		PIG = new EntityType(NamespacedKey.MINECRAFT, "PIG", CorePig.class);
		PIGLIN = new EntityType(NamespacedKey.MINECRAFT, "PIGLIN", CorePiglin.class);
		PIGLIN_BRUTE = new EntityType(NamespacedKey.MINECRAFT, "PIGLIN_BRUTE", CorePiglinBrute.class);
		PILLAGER = new EntityType(NamespacedKey.MINECRAFT, "PILLAGER", CorePillager.class);
		POLAR_BEAR = new EntityType(NamespacedKey.MINECRAFT, "POLAR_BEAR", CorePolarBear.class);
		TNT = new EntityType(NamespacedKey.MINECRAFT, "TNT", CorePrimedTNT.class);
		PUFFERFISH = new EntityType(NamespacedKey.MINECRAFT, "PUFFERFISH", CorePufferFish.class);
		RABBIT = new EntityType(NamespacedKey.MINECRAFT, "RABBIT", CoreRabbit.class);
		RAVAGER = new EntityType(NamespacedKey.MINECRAFT, "RAVAGER", CoreRavager.class);
		SALMON = new EntityType(NamespacedKey.MINECRAFT, "SALMON", CoreSalmon.class);
		SHEEP = new EntityType(NamespacedKey.MINECRAFT, "SHEEP", CoreSheep.class);
		SHULKER = new EntityType(NamespacedKey.MINECRAFT, "SHULKER", CoreShulker.class);
		SHULKER_BULLET = new EntityType(NamespacedKey.MINECRAFT, "SHULKER_BULLET", CoreShulkerBullet.class);
		SILVERFISH = new EntityType(NamespacedKey.MINECRAFT, "SILVERFISH", CoreSilverfish.class);
		SKELETON = new EntityType(NamespacedKey.MINECRAFT, "SKELETON", CoreSkeleton.class);
		SKELETON_HORSE = new EntityType(NamespacedKey.MINECRAFT, "SKELETON_HORNE", CoreSkeletonHorse.class);
		SLIME = new EntityType(NamespacedKey.MINECRAFT, "SLIME", CoreSlime.class);
		SMALL_FIREBALL = new EntityType(NamespacedKey.MINECRAFT, "SMALL_FIREBALL", CoreSmallFireball.class);
		SNOW_GOLEM = new EntityType(NamespacedKey.MINECRAFT, "SNOW_GOLEM", CoreSnowGolem.class);
		SNOWBALL = new EntityType(NamespacedKey.MINECRAFT, "SNOWBALL", CoreSnowball.class);
		SPECTRAL_ARROW = new EntityType(NamespacedKey.MINECRAFT, "SPECTRAL_ARROW", CoreSpectralArrow.class);
		SPIDER = new EntityType(NamespacedKey.MINECRAFT, "SPIDER", CoreSpider.class);
		SQUID = new EntityType(NamespacedKey.MINECRAFT, "SQUID", CoreSquid.class);
		STRAY = new EntityType(NamespacedKey.MINECRAFT, "STRAY", CoreStray.class);
		STRIDER = new EntityType(NamespacedKey.MINECRAFT, "STRIDER", CoreStrider.class);
		EGG = new EntityType(NamespacedKey.MINECRAFT, "EGG", CoreEgg.class);
		ENDER_PEARL = new EntityType(NamespacedKey.MINECRAFT, "ENDER_PEARL", CoreEnderPearl.class);
		EXPERIENCE_BOTTLE = new EntityType(NamespacedKey.MINECRAFT, "EXPERIENCE_BOTTLE", CoreExpBottle.class);
		POTION = new EntityType(NamespacedKey.MINECRAFT, "POTION", CorePotion.class);
		TRIDENT = new EntityType(NamespacedKey.MINECRAFT, "TRIDENT", CoreTrident.class);
		TRADER_LLAMA = new EntityType(NamespacedKey.MINECRAFT, "TRADER_LLAMA", CoreTraderLlama.class);
		TROPICAL_FISH = new EntityType(NamespacedKey.MINECRAFT, "TROPICAL_FISH", CoreTropicalFish.class);
		TURTLE = new EntityType(NamespacedKey.MINECRAFT, "TRUTLE", CoreTurtle.class);
		VEX = new EntityType(NamespacedKey.MINECRAFT, "VEX", CoreVex.class);
		VILLAGER = new EntityType(NamespacedKey.MINECRAFT, "VILLAGER", CoreVillager.class);
		VINDICATOR = new EntityType(NamespacedKey.MINECRAFT, "VINDICATOR", CoreVindicator.class);
		WANDERING_TRADER = new EntityType(NamespacedKey.MINECRAFT, "WANDERING_TRADER", CoreWanderingTrader.class);
		WITCH = new EntityType(NamespacedKey.MINECRAFT, "WITCH", CoreWitch.class);
		WITHER = new EntityType(NamespacedKey.MINECRAFT, "WITHER", CoreWither.class);
		WITHER_SKELETON = new EntityType(NamespacedKey.MINECRAFT, "WITHER_SKELETON", CoreWitherSkeleton.class);
		WITHER_SKULL = new EntityType(NamespacedKey.MINECRAFT, "WITHER_SKULL", CoreWitherSkull.class);
		WOLF = new EntityType(NamespacedKey.MINECRAFT, "WOLF", CoreWolf.class);
		ZOGLIN = new EntityType(NamespacedKey.MINECRAFT, "ZOGLIN", CoreZoglin.class);
		ZOMBIE = new EntityType(NamespacedKey.MINECRAFT, "ZOMBIE", CoreZombie.class);
		ZOMBIE_HORSE = new EntityType(NamespacedKey.MINECRAFT, "ZOMBIE_HORSE", CoreZombieHorse.class);
		ZOMBIE_VILLAGER = new EntityType(NamespacedKey.MINECRAFT, "ZOMBIFIED_VILLAGER", CoreZombieVillager.class);
		ZOMBIFIED_PIGLIN = new EntityType(NamespacedKey.MINECRAFT, "ZOMBIEFIED_PIGLIN", CoreZombifiedPiglin.class);
		PLAYER = new EntityType(NamespacedKey.MINECRAFT, "PLAYER", CorePlayer.class);
		FISHING_BOBBER = new EntityType(NamespacedKey.MINECRAFT, "FISHING_BOBBER", CoreFishingHook.class);
	}

}
