package de.atlascore.system.init;

import static de.atlasmc.entity.EntityType.*;

import de.atlascore.entity.*;
import de.atlasmc.NamespacedKey;
import de.atlasmc.entity.EntityType;

public class EntityTypeLoader {
	
	public static void loadEntityTypes() {
		AREA_EFFECT_CLOUD = new EntityType(NamespacedKey.MINECRAFT, "area_effect_cloud", CoreAreaEffectCloud.class);
		ARMOR_STAND = new EntityType(NamespacedKey.MINECRAFT, "armor_stand", CoreArmorStand.class);
		ARROW = new EntityType(NamespacedKey.MINECRAFT, "arrow", CoreArrow.class);
		BAT = new EntityType(NamespacedKey.MINECRAFT, "bat", CoreBat.class); 
		BEE = new EntityType(NamespacedKey.MINECRAFT, "bee", CoreBee.class);
		BLAZE = new EntityType(NamespacedKey.MINECRAFT, "blaze", CoreBlaze.class);
		BOAT = new EntityType(NamespacedKey.MINECRAFT, "boat", CoreBoat.class);
		CAT = new EntityType(NamespacedKey.MINECRAFT, "cat", CoreCow.class);
		CAVE_SPIDER = new EntityType(NamespacedKey.MINECRAFT, "cave_spider", CoreCaveSpider.class);
		CHICKEN = new EntityType(NamespacedKey.MINECRAFT, "chicken", CoreChicken.class);
		COD = new EntityType(NamespacedKey.MINECRAFT, "cod", CoreCod.class);
		COW = new EntityType(NamespacedKey.MINECRAFT, "cow", CoreCow.class);
		CREEPER = new EntityType(NamespacedKey.MINECRAFT, "creeper", CoreCreeper.class);
		DOLPHIN = new EntityType(NamespacedKey.MINECRAFT, "dolphin", CoreDolphin.class);
		DONKEY = new EntityType(NamespacedKey.MINECRAFT, "donkey", CoreDonkey.class);
		DRAGON_FIREBALL = new EntityType(NamespacedKey.MINECRAFT, "dragon_fireball", CoreDragonFireball.class);
		DROWNED = new EntityType(NamespacedKey.MINECRAFT, "drowned", CoreDrowned.class);
		ELDER_GUARDIAN = new EntityType(NamespacedKey.MINECRAFT, "elder_guardian", CoreElderGuardian.class);
		END_CRYSTAL = new EntityType(NamespacedKey.MINECRAFT, "end_crystal", CoreEndCrystal.class);
		ENDER_DRAGON = new EntityType(NamespacedKey.MINECRAFT, "ender_dragon", CoreEnderDragon.class);
		ENDERMAN = new EntityType(NamespacedKey.MINECRAFT, "enderman", CoreEnderman.class);
		ENDERMITE = new EntityType(NamespacedKey.MINECRAFT, "endermite", CoreEndermite.class);
		EVOKER = new EntityType(NamespacedKey.MINECRAFT, "evoker", CoreEvoker.class);
		EVOKER_FANGS = new EntityType(NamespacedKey.MINECRAFT, "evoker_fangs", CoreEvokerFangs.class);
		EXPERIENCE_ORB = new EntityType(NamespacedKey.MINECRAFT, "experience_orb", CoreExperienceOrb.class);
		EYE_OF_ENDER = new EntityType(NamespacedKey.MINECRAFT, "eye_of_ender", CoreEyeOfEnder.class);
		FALLING_BLOCK = new EntityType(NamespacedKey.MINECRAFT, "falling_block", CoreFallingBlock.class);
		FIREWORK_ROCKET = new EntityType(NamespacedKey.MINECRAFT, "firework_rocket", CoreFireworkRocket.class);
		FOX = new EntityType(NamespacedKey.MINECRAFT, "fox", CoreFox.class);
		GHAST = new EntityType(NamespacedKey.MINECRAFT, "ghast", CoreGhast.class);
		GIANT = new EntityType(NamespacedKey.MINECRAFT, "giant", CoreGiant.class);
		GUARDIAN = new EntityType(NamespacedKey.MINECRAFT, "guardian", CoreGuardian.class);
		HORSE = new EntityType(NamespacedKey.MINECRAFT, "horse", CoreHorse.class);
		HOGLIN = new EntityType(NamespacedKey.MINECRAFT, "hoglin", CoreHoglin.class);
		HUSK = new EntityType(NamespacedKey.MINECRAFT, "husk", CoreHusk.class);
		ILLUSIONER = new EntityType(NamespacedKey.MINECRAFT, "illusioner", CoreIllusioner.class);
		IRON_GOLEM = new EntityType(NamespacedKey.MINECRAFT, "iron_golem", CoreIronGolem.class);
		ITEM = new EntityType(NamespacedKey.MINECRAFT, "item", CoreItem.class);
		ITEM_FRAME = new EntityType(NamespacedKey.MINECRAFT, "item_frame", CoreItemFrame.class);
		FIREBALL = new EntityType(NamespacedKey.MINECRAFT, "fireball", CoreLargeFireball.class);
		LEASH_KNOT = new EntityType(NamespacedKey.MINECRAFT, "leash_knot", CoreLeashKnot.class);
		LIGHTNING_BOLT = new EntityType(NamespacedKey.MINECRAFT, "lightning_bolt", CoreLightningBolt.class);
		LLAMA = new EntityType(NamespacedKey.MINECRAFT, "llama", CoreLlama.class);
		LLAMA_SPIT = new EntityType(NamespacedKey.MINECRAFT, "llama_spit", CoreLlamaSpit.class);
		MAGMA_CUBE = new EntityType(NamespacedKey.MINECRAFT, "magma_cube", CoreMagmaCube.class);
		MINECART = new EntityType(NamespacedKey.MINECRAFT, "minecart", CoreMinecart.class);
		CHEST_MINECART = new EntityType(NamespacedKey.MINECRAFT, "chest_minecart", CoreMinecartChest.class);
		COMMAND_BLOCK_MINECART = new EntityType(NamespacedKey.MINECRAFT, "command_block_minecart", CoreMinecartCommandBlock.class);
		FURNACE_MINECART = new EntityType(NamespacedKey.MINECRAFT, "furnace_minecart", CoreMinecraftFurnace.class);
		HOPPER_MINECART = new EntityType(NamespacedKey.MINECRAFT, "hopper_minecart", CoreMinecartHopper.class);
		SPAWNER_MINECART = new EntityType(NamespacedKey.MINECRAFT, "spawner_minecart", CoreMinecartSpawner.class);
		TNT_MINECART = new EntityType(NamespacedKey.MINECRAFT, "tnt_minecart", CoreMinecartTNT.class);
		MULE = new EntityType(NamespacedKey.MINECRAFT, "mule", CoreMule.class);
		MOOSHROOM = new EntityType(NamespacedKey.MINECRAFT, "mooshroom", CoreMooshroom.class);
		OCELOT = new EntityType(NamespacedKey.MINECRAFT, "ocelot", CoreOcelot.class);
		PAINTING = new EntityType(NamespacedKey.MINECRAFT, "painting", CorePainting.class);
		PANDA = new EntityType(NamespacedKey.MINECRAFT, "panda", CorePanda.class);
		PARROT = new EntityType(NamespacedKey.MINECRAFT, "parrot", CoreParrot.class);
		PHANTOM = new EntityType(NamespacedKey.MINECRAFT, "phantom", CorePhantom.class);
		PIG = new EntityType(NamespacedKey.MINECRAFT, "pig", CorePig.class);
		PIGLIN = new EntityType(NamespacedKey.MINECRAFT, "piglin", CorePiglin.class);
		PIGLIN_BRUTE = new EntityType(NamespacedKey.MINECRAFT, "piglin_brute", CorePiglinBrute.class);
		PILLAGER = new EntityType(NamespacedKey.MINECRAFT, "pillager", CorePillager.class);
		POLAR_BEAR = new EntityType(NamespacedKey.MINECRAFT, "polar_bear", CorePolarBear.class);
		PRIMED_TNT = new EntityType(NamespacedKey.MINECRAFT, "tnt", CorePrimedTNT.class);
		PUFFERFISH = new EntityType(NamespacedKey.MINECRAFT, "pufferfish", CorePufferFish.class);
		RABBIT = new EntityType(NamespacedKey.MINECRAFT, "rabbit", CoreRabbit.class);
		RAVAGER = new EntityType(NamespacedKey.MINECRAFT, "ravager", CoreRavager.class);
		SALMON = new EntityType(NamespacedKey.MINECRAFT, "salmon", CoreSalmon.class);
		SHEEP = new EntityType(NamespacedKey.MINECRAFT, "sheep", CoreSheep.class);
		SHULKER = new EntityType(NamespacedKey.MINECRAFT, "shulker", CoreShulker.class);
		SHULKER_BULLET = new EntityType(NamespacedKey.MINECRAFT, "shulker_bullet", CoreShulkerBullet.class);
		SILVERFISH = new EntityType(NamespacedKey.MINECRAFT, "silverfish", CoreSilverfish.class);
		SKELETON = new EntityType(NamespacedKey.MINECRAFT, "skeleton", CoreSkeleton.class);
		SKELETON_HORSE = new EntityType(NamespacedKey.MINECRAFT, "skeleton_horse", CoreSkeletonHorse.class);
		SLIME = new EntityType(NamespacedKey.MINECRAFT, "slime", CoreSlime.class);
		SMALL_FIREBALL = new EntityType(NamespacedKey.MINECRAFT, "small_fireball", CoreSmallFireball.class);
		SNOW_GOLEM = new EntityType(NamespacedKey.MINECRAFT, "snow_golem", CoreSnowGolem.class);
		SNOWBALL = new EntityType(NamespacedKey.MINECRAFT, "snowball", CoreSnowball.class);
		SPECTRAL_ARROW = new EntityType(NamespacedKey.MINECRAFT, "spectral_arrow", CoreSpectralArrow.class);
		SPIDER = new EntityType(NamespacedKey.MINECRAFT, "spider", CoreSpider.class);
		SQUID = new EntityType(NamespacedKey.MINECRAFT, "squid", CoreSquid.class);
		STRAY = new EntityType(NamespacedKey.MINECRAFT, "stray", CoreStray.class);
		STRIDER = new EntityType(NamespacedKey.MINECRAFT, "strider", CoreStrider.class);
		EGG = new EntityType(NamespacedKey.MINECRAFT, "egg", CoreEgg.class);
		ENDER_PEARL = new EntityType(NamespacedKey.MINECRAFT, "ender_pearl", CoreEnderPearl.class);
		EXPERIENCE_BOTTLE = new EntityType(NamespacedKey.MINECRAFT, "experience_bottle", CoreExpBottle.class);
		POTION = new EntityType(NamespacedKey.MINECRAFT, "potion", CorePotion.class);
		TRIDENT = new EntityType(NamespacedKey.MINECRAFT, "trident", CoreTrident.class);
		TRADER_LLAMA = new EntityType(NamespacedKey.MINECRAFT, "trader_llama", CoreTraderLlama.class);
		TROPICAL_FISH = new EntityType(NamespacedKey.MINECRAFT, "tropical_fish", CoreTropicalFish.class);
		TURTLE = new EntityType(NamespacedKey.MINECRAFT, "turtle", CoreTurtle.class);
		VEX = new EntityType(NamespacedKey.MINECRAFT, "vex", CoreVex.class);
		VILLAGER = new EntityType(NamespacedKey.MINECRAFT, "villager", CoreVillager.class);
		VINDICATOR = new EntityType(NamespacedKey.MINECRAFT, "vindicator", CoreVindicator.class);
		WANDERING_TRADER = new EntityType(NamespacedKey.MINECRAFT, "wandering_trader", CoreWanderingTrader.class);
		WITCH = new EntityType(NamespacedKey.MINECRAFT, "witch", CoreWitch.class);
		WITHER = new EntityType(NamespacedKey.MINECRAFT, "wither", CoreWither.class);
		WITHER_SKELETON = new EntityType(NamespacedKey.MINECRAFT, "wither_skeleton", CoreWitherSkeleton.class);
		WITHER_SKULL = new EntityType(NamespacedKey.MINECRAFT, "wither_skull", CoreWitherSkull.class);
		WOLF = new EntityType(NamespacedKey.MINECRAFT, "wolf", CoreWolf.class);
		ZOGLIN = new EntityType(NamespacedKey.MINECRAFT, "zoglin", CoreZoglin.class);
		ZOMBIE = new EntityType(NamespacedKey.MINECRAFT, "zombie", CoreZombie.class);
		ZOMBIE_HORSE = new EntityType(NamespacedKey.MINECRAFT, "zombie_horse", CoreZombieHorse.class);
		ZOMBIE_VILLAGER = new EntityType(NamespacedKey.MINECRAFT, "zombified_villager", CoreZombieVillager.class);
		ZOMBIFIED_PIGLIN = new EntityType(NamespacedKey.MINECRAFT, "zombified_piglin", CoreZombifiedPiglin.class);
		PLAYER = new EntityType(NamespacedKey.MINECRAFT, "player", CorePlayer.class);
		FISHING_BOBBER = new EntityType(NamespacedKey.MINECRAFT, "fishing_bobber", CoreFishingHook.class);
	}

}
