package de.atlascore.system.init;

import static de.atlasmc.entity.EntityType.*;

import de.atlascore.entity.*;
import de.atlasmc.entity.EntityType;

public class EntityTypeLoader {
	
	public static void loadEntityTypes() {
		AREA_EFFECT_CLOUD = new EntityType(0, "AREA_EFFECT_CLOUD", CoreAreaEffectCloud.class);
		ARMOR_STAND = new EntityType(0, "ArmorStand", CoreArmorStand.class);
		ARROW = new EntityType(0, "ARROW", CoreArrow.class);
		BAT = new EntityType(0, "BAT", CoreBat.class); 
		BEE = new EntityType(0, "BEE", CoreBee.class);
		BLAZE = new EntityType(0, "BLAZE", null);
		BOAT = new EntityType(0, "BOAT", CoreBoat.class);
		CAT = new EntityType(0, "CAT", CoreCow.class);
		CAVE_SPIDER = new EntityType(0, "CAVE_SPIDER", null);
		CHICKEN = new EntityType(0, "CHICKEN", CoreChicken.class);
		COD = new EntityType(0, "COD", CoreCod.class);
		COW = new EntityType(0, "COW", CoreCow.class);
		CREEPER = new EntityType(0, "CREEPER", null);
		DOLPHIN = new EntityType(0, "DOLPHIN", CoreDolphin.class);
		DONKEY = new EntityType(0, "DONKEY", CoreDonkey.class);
		DRAGON_FIREBALL = new EntityType(0, "DRAGON_FIREBALL", CoreDragonFireball.class);
		DROWNED = new EntityType(0, "DROWNED", null);
		ELDER_GUARDIAN = new EntityType(0, "ELDER_GUARDIAN", null);
		END_CRYSTAL = new EntityType(0, "END_CRYSTAL", CoreEndCrystal.class);
		ENDER_DRAGON = new EntityType(0, "ENDER_DRAGON", null);
		ENDERMAN = new EntityType(0, "ENDERMAN", null);
		ENDERMITE = new EntityType(0, "ENDERMITE", null);
		EVOKER = new EntityType(0, "EVOKER", null);
		EVOKER_FANGS = new EntityType(0, "EVOKER_FANGS", null);
		EXPERIENCE_ORB = new EntityType(0, "EXPERIENCE_ORB", null);
		EYE_OF_ENDER = new EntityType(0, "EYE_OF_ENDER", CoreEyeOfEnder.class);
		FALLING_BLOCK = new EntityType(0, "FALLING_BLOCK", CoreFallingBlock.class);
		FIREWORK_ROCKET = new EntityType(0, "FIREWORK_ROCKET", CoreFireworkRocket.class);
		FOX = new EntityType(0, "FOX", CoreFox.class);
		GHAST = new EntityType(0, "GHAST", null);
		GIANT = new EntityType(0, "GIANT", null);
		GUARDIAN = new EntityType(0, "GUARDIAN", null);
		HORSE = new EntityType(0, "HORSE", CoreHorse.class);
		HOGLIN = new EntityType(0, "HOGLIN", CoreHoglin.class);
		HUSK = new EntityType(0, "HUSK", null);
		ILLUSIONER = new EntityType(0, "ILLUSIONER", null);
		IRON_GOLEM = new EntityType(0, "IRON_GOLEM", CoreIronGolem.class);
		ITEM = new EntityType(0, "ITEM", CoreItem.class);
		ITEM_FRAME = new EntityType(0, "ITEM_FRAME", CoreItemFrame.class);
		FIREBALL = new EntityType(0, "FIREBALL", CoreLargeFireball.class);
		LEASH_KNOT = new EntityType(0, "LEASH_KNOT", null);
		LIGHTNING_BOLT = new EntityType(0, "LIGHTNING_BOLT", null);
		LLAMA = new EntityType(0, "LLAMA", CoreLlama.class);
		LLAMA_SPIT = new EntityType(0, "LLAMA_SPIT", null);
		MAGMA_CUBE = new EntityType(0, "MAGMA_CUBE", null);
		MINECART = new EntityType(0, "MINECART", null);
		CHEST_MINECART = new EntityType(0, "CHEST_MINECART", null);
		COMMAND_BLOCK_MINECART = new EntityType(0, "COMMAND_BLOCK_MINECART", null);
		FURNACE_MINECART = new EntityType(0, "FURNACE_MINECART", null);
		HOPPER_MINECART = new EntityType(0, "HOPPER_MINECART", null);
		SPAWNER_MINECART = new EntityType(0, "SPAWNER_MINECART", null);
		TNT_MINECART = new EntityType(0, "TNT_MINECART", null);
		MULE = new EntityType(0, "MULE", CoreMule.class);
		MOOSHROOM = new EntityType(0, "MOOSHROOM", CoreMooshroom.class);
		OCELOT = new EntityType(0, "OCELOT", CoreOcelot.class);
		PAINTING = new EntityType(0, "PAINTING", null);
		PANDA = new EntityType(0, "PANDA", CorePanda.class);
		PARROT = new EntityType(0, "PARROT", CoreParrot.class);
		PHANTOM = new EntityType(0, "PHANTOM", null);
		PIG = new EntityType(0, "PIG", CorePig.class);
		PIGLIN = new EntityType(0, "PIGLIN", null);
		PIGLIN_BRUTE = new EntityType(0, "PIGLIN_BRUTE", null);
		PILLAGER = new EntityType(0, "PILLAGER", null);
		POLAR_BEAR = new EntityType(0, "POLAR_BEAR", CorePolarBear.class);
		TNT = new EntityType(0, "TNT", null);
		PUFFERFISH = new EntityType(0, "PUFFERFISH", CorePufferFish.class);
		RABBIT = new EntityType(0, "RABBIT", CoreRabbit.class);
		RAVAGER = new EntityType(0, "RAVAGER", null);
		SALMON = new EntityType(0, "SALMON", CoreSalmon.class);
		SHEEP = new EntityType(0, "SHEEP", CoreSheep.class);
		SHULKER = new EntityType(0, "SHULKER", CoreShulker.class);
		SHULKER_BULLET = new EntityType(0, "SHULKER_BULLET", null);
		SILVERFISH = new EntityType(0, "SILVERFISH", null);
		SKELETON = new EntityType(0, "SKELETON", null);
		SKELETON_HORSE = new EntityType(0, "SKELETON_HORNE", CoreSkeletonHorse.class);
		SLIME = new EntityType(0, "SLIME", null);
		SMALL_FIREBALL = new EntityType(0, "SMALL_FIREBALL", CoreSmallFireball.class);
		SNOW_GOLEM = new EntityType(0, "SNOW_GOLEM", CoreSnowGolem.class);
		SNOWBALL = new EntityType(0, "SNOWBALL", null);
		SPECTRAL_ARROW = new EntityType(0, "SPECTRAL_ARROW", CoreSpectralArrow.class);
		SPIDER = new EntityType(0, "SPIDER", null);
		SQUID = new EntityType(0, "SQUID", CoreSquid.class);
		STRAY = new EntityType(0, "STRAY", null);
		STRIDER = new EntityType(0, "STRIDER", null);
		EGG = new EntityType(0, "EGG", CoreEgg.class);
		ENDER_PEARL = new EntityType(0, "ENDER_PEARL", CoreEnderPearl.class);
		EXPERIENCE_BOTTLE = new EntityType(0, "EXPERIENCE_BOTTLE", CoreExpBottle.class);
		POTION = new EntityType(0, "POTION", CorePotion.class);
		TRIDENT = new EntityType(0, "TRIDENT", CoreTrident.class);
		TRADER_LLAMA = new EntityType(0, "TRADER_LLAMA", null);
		TROPICAL_FISH = new EntityType(0, "TROPICAL_FISH", null);
		TURTLE = new EntityType(0, "TRUTLE", CoreTurtle.class);
		VEX = new EntityType(0, "VEX", null);
		VILLAGER = new EntityType(0, "VILLAGER", CoreVillager.class);
		VINDICATOR = new EntityType(0, "VINDICATOR", null);
		WANDERING_TRADER = new EntityType(0, "WANDERING_TRADER", CoreWanderingTrader.class);
		WITCH = new EntityType(0, "WITCH", null);
		WITHER = new EntityType(0, "WITHER", null);
		WITHER_SKELETON = new EntityType(0, "WITHER_SKELETON", null);
		WITHER_SKULL = new EntityType(0, "WITHER_SKULL", CoreWitherSkull.class);
		WOLF = new EntityType(0, "WOLF", CoreWolf.class);
		ZOGLIN = new EntityType(0, "ZOGLIN", null);
		ZOMBIE = new EntityType(0, "ZOMBIE", null);
		ZOMBIE_HORSE = new EntityType(0, "ZOMBIE_HORSE", CoreZombieHorse.class);
		ZOMBIE_VILLAGER = new EntityType(0, "ZOMBIFIED_VILLAGER", null);
		ZOMBIFIED_PIGLIN = new EntityType(0, "ZOMBIEFIED", null);
		PLAYER = new EntityType(0, "PLAYER", CorePlayer.class);
		FISHING_BOBBER = new EntityType(0, "FISHING_BOBBER", CoreFishingHook.class);
	}

}
