package de.atlasmc.event.inventory;

public enum InventoryAction {
	
	CLONE_STACK,
	COLLECT_TO_CURSOR,
	DROP_ALL_CURSOR,
	DROP_ALL_SLOT,
	DROP_ONE_CURSOR,
	DROP_ONE_SLOT,
	HOTBAR_MOVE_AND_READD,
	HOTBAR_SWAP,
	MOVE_TO_OTHER_INVENTORY,
	NOTHING,
	PICKUP_ALL,
	PICKUP_HALF,
	PICKUP_ONE,
	PICKUP_SOME,
	PLACE_ALL,
	PLACE_ONE,
	PLACE_SOME,
	SWAP_WITH_CURSOR,
	UNKNOWN;

}
