package de.atlasmc.node.recipe;

import de.atlasmc.util.enums.EnumName;

public enum RecipeType implements EnumName {
	
	CRAFTING_SHAPELESS,
	CRAFTING_SHAPED,
	SMELTING,
	BLASTING,
	SMOKING,
	CAMPFIRE_COOKING,
	STONECUTTING,
	SMITHING_TRIM,
	SMITHING_TRANSFORM,
	CRAFTING_SPECIAL_ARMORDYE,
	CRAFTING_SPECIAL_BOOKCLONING,
	CRAFTING_SPECIAL_MAPCLONING,
	CRAFTING_SPECIAL_MAPEXTENDING,
	CRAFTING_SPECIAL_FIREWORK_ROCKET,
	CRAFTING_SPECIAL_FIREWORK_STAR,
	CRAFTING_SPECIAL_FIREWORK_STAR_FADE,
	CRAFTING_SPECIAL_REPAIR_ITEM,
	CRAFTING_SPECIAL_TIPPEDARROW,
	CRAFTING_SPECIAL_BANNERDUPLICATE,
	CRAFTING_SPECIAL_SHIELDDECORATION,
	CRAFTING_SPECIAL_SHULKERBOXCOLORING,
	CRAFTING_SPECIAL_SUSPICIOUSSTEW,
	CRAFTING_DECORATED_POT;
	
	private String name;
	
	private RecipeType() {
		this.name = "minecraft:" + name().toLowerCase();
	}
	
	@Override
	public String getName() {
		return name;
	}
	
	public Recipe createRecipe() {
		throw new UnsupportedOperationException("Not implemented!");
	}
	
}
