package de.atlasmc;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import de.atlascore.inventory.meta.CoreItemMeta;
import de.atlasmc.block.data.Ageable;
import de.atlasmc.block.data.AnaloguePowerable;
import de.atlasmc.block.data.Bed;
import de.atlasmc.block.data.Bisected;
import de.atlasmc.block.data.BlockData;
import de.atlasmc.block.data.BrewingStand;
import de.atlasmc.block.data.Cake;
import de.atlasmc.block.data.Chain;
import de.atlasmc.block.data.Chest;
import de.atlasmc.block.data.Cocoa;
import de.atlasmc.block.data.CommandBlock;
import de.atlasmc.block.data.Comparator;
import de.atlasmc.block.data.DaylightDetectore;
import de.atlasmc.block.data.Directional;
import de.atlasmc.block.data.Dispenser;
import de.atlasmc.block.data.Door;
import de.atlasmc.block.data.EndPortalFrame;
import de.atlasmc.block.data.EnderChest;
import de.atlasmc.block.data.Farmland;
import de.atlasmc.block.data.Fence;
import de.atlasmc.block.data.Fire;
import de.atlasmc.block.data.Furnace;
import de.atlasmc.block.data.Gate;
import de.atlasmc.block.data.Hopper;
import de.atlasmc.block.data.Jukebox;
import de.atlasmc.block.data.Ladder;
import de.atlasmc.block.data.Leaves;
import de.atlasmc.block.data.Levelled;
import de.atlasmc.block.data.Lightable;
import de.atlasmc.block.data.MultipleFacing;
import de.atlasmc.block.data.NoteBlock;
import de.atlasmc.block.data.Orientable;
import de.atlasmc.block.data.Pistion;
import de.atlasmc.block.data.PistionHead;
import de.atlasmc.block.data.Powerable;
import de.atlasmc.block.data.Rail;
import de.atlasmc.block.data.RedstoneRail;
import de.atlasmc.block.data.RedstoneWallTorch;
import de.atlasmc.block.data.RedstoneWire;
import de.atlasmc.block.data.Repeater;
import de.atlasmc.block.data.Rotatable;
import de.atlasmc.block.data.Sapling;
import de.atlasmc.block.data.Sign;
import de.atlasmc.block.data.Snow;
import de.atlasmc.block.data.Snowable;
import de.atlasmc.block.data.Stairs;
import de.atlasmc.block.data.Switch;
import de.atlasmc.block.data.TechnicalPistion;
import de.atlasmc.block.data.TrapDoor;
import de.atlasmc.block.data.Tripwire;
import de.atlasmc.block.data.TripwireHook;
import de.atlasmc.block.data.Wall;
import de.atlasmc.block.data.WallSign;
import de.atlasmc.factory.metadata.ClassMetaDataFactory;
import de.atlasmc.factory.metadata.MetaDataFactory;
import de.atlasmc.inventory.meta.ItemMeta;

public class Material {
	
	private static final HashMap<String, Material> BY_NAME;
	private static final HashMap<Material, MetaDataFactory> META_FACTORYS;
	private static short iid;
	
	public static final Material
	AIR,
	STONE,
	GRANITE,
	POLISHED_GRANITE,
	DIORITE,
	POLISHED_DIORITE,
	ANDESITE,
	POLISHED_ANDESITE,
	GRASS_BLOCK,
	DIRT,
	COARSE_DIRT,
	PODZOL,
	CRIMSON_NYLIUM,
	WARPED_NYLIUM,
	COBBLESTONE,
	OAK_PLANKS,
	SPRUCE_PLANKS,
	BIRCH_PLANKS,
	JUNGLE_PLANKS,
	ACACIA_PLANKS,
	DARK_OAK_PLANKS,
	CRIMSON_PLANKS,
	WARPED_PLANKS,
	OAK_SAPLING,
	SPRUCE_SAPLING,
	BIRCH_SAPLING,
	JUNGLE_SAPLING,
	ACACIA_SAPLING,
	DARK_OAK_SAPLING,
	BEDROCK,
	WATER,
	LAVA,
	SAND,
	RED_SAND,
	GRAVEL,
	GOLD_ORE,
	IRON_ORE,
	COAL_ORE,
	NETHER_GOLD_ORE,
	OAK_LOG,
	SPRUCE_LOG,
	BIRCH_LOG,
	JUNGLE_LOG,
	ACACIA_LOG,
	DARK_OAK_LOG,
	CRIMSON_STEM,
	WARPED_STEM,
	STRIPPED_OAK_LOG,
	STRIPPED_SPRUCE_LOG,
	STRIPPED_BIRCH_LOG,
	STRIPPED_JUNGLE_LOG,
	STRIPPED_ACACIA_LOG,
	STRIPPED_DARK_OAK_LOG,
	STRIPPED_CRIMSON_STEM,
	STRIPPED_WARPED_STEM,
	STRIPPED_OAK_WOOD,
	STRIPPED_SPRUCE_WOOD,
	STRIPPED_BIRCH_WOOD,
	STRIPPED_JUNGLE_WOOD,
	STRIPPED_ACACIA_WOOD,
	STRIPPED_DARK_OAK_WOOD,
	STRIPPED_CRIMSON_HYPHAE,
	STRIPPED_WARPED_HYPHAE,
	OAK_WOOD,
	SPRUCE_WOOD,
	BIRCH_WOOD,
	JUNGLE_WOOD,
	ACACIA_WOOD,
	DARK_OAK_WOOD,
	CRIMSON_HYPHAE,
	WARPED_HYPHAE,
	OAK_LEAVES,
	SPRUCE_LEAVES,
	BIRCH_LEAVES,
	JUNGLE_LEAVES,
	ACACIA_LEAVES,
	DARK_OAK_LEAVES,
	SPONGE,
	WET_SPONGE,
	GLASS,
	LAPIS_ORE,
	LAPIS_BLOCK,
	DISPENSER,
	SANDSTONE,
	CHISELED_SANDSTONE,
	CUT_SANDSTONE,
	NOTE_BLOCK,
	POWERED_RAIL,
	DETECTOR_RAIL,
	STICKY_PISTION,
	COBWEB,
	GRASS,
	FERN,
	DEAD_BUSH,
	SEAGRASS,
	TALL_SEAGRASS,
	SEA_PICKLE,
	PISTION,
	PISTION_HEAD,
	MOVING_PISTION,
	WHITE_WOOL,
	ORANGE_WOOL,
	MAGENTA_WOOL,
	LIGHT_BLUE_WOOL,
	YELLOW_WOOL,
	LIME_WOOL,
	PINK_WOOL,
	GRAY_WOOL,
	LIGHT_GRAY_WOOL,
	CYAN_WOOL,
	PURPLE_WOOL,
	BLUE_WOOL,
	BROWN_WOOL,
	GREEN_WOOL,
	RED_WOOL,
	BLACK_WOOL,
	DANDELION,
	POPPY,
	BLUE_ORCHID,
	ALLIUM,
	AZURE_BLUET,
	RED_TULIP,
	ORANGE_TULIP,
	WHITE_TULIP,
	PINK_TULIP,
	OXEYE_DAISY,
	CORNFLOWER,
	LILY_OF_THE_VALLEY,
	WITHER_ROSE,
	BROWN_MUSHROOM,
	RED_MUSHROOM,
	CRIMSON_FUNGUS,
	WARPED_FUNGUS,
	CRIMSON_ROOTS,
	WARPED_ROOTS,
	NETHER_SPROUTS,
	WEEPING_VINES,
	TWISTING_VINES,
	SUGAR_CANE,
	KELP,
	BAMBOO,
	GOLD_BLOCK,
	IRON_BLOCK,
	OAK_SLAB,
	SPRUCE_SLAB,
	BIRCH_SLAB,
	JUNGLE_SLAB,
	ACACIA_SLAB,
	DARK_OAK_SLAB,
	CRIMSON_SLAB,
	WARPED_SLAB,
	STONE_SLAB,
	SMOOTH_STONE_SLAB,
	SANDSTONE_SLAB,
	CUT_SANDSTONE_SLAB,
	PETRIFIED_OAK_SLAB,
	COBBLESTONE_SLAB,
	BRICK_SLAB,
	STONE_BRICK_SLAB,
	NETHER_BRICK_SLAB,
	QUARTZ_SLAB,
	RED_SANDSTONE_SLAB,
	CUT_RED_SANDSTONE_SLAB,
	PURPUR_SLAB,
	PRISMARINE_SLAB,
	PRISMARINE_BRICK_SLAB,
	DARK_PRISMARINE_SLAB,
	SMOOTH_QUARTZ,
	SMOOTH_RED_SANDSTONE,
	SMOOTH_SANDSTONE,
	SMOOTH_STONE,
	BRICKS,
	TNT,
	BOOKSHELF,
	MOSSY_COBBLESTONE,
	OBSIDIAN,
	TORCH,
	WALL_TORCH,
	FIRE,
	SOUL_FIRE,
	END_ROD,
	CHORUS_PLANT,
	CHORUS_FLOWER,
	PURPUR_BLOCK,
	PURPUR_PILLAR,
	PURPUR_STAIRS,
	SPAWNER,
	OAK_STAIRS,
	CHEST,
	REDSTONE_WIRE,
	DIAMOND_ORE,
	DIAMOND_BLOCK,
	CRAFTING_TABLE,
	FARMLAND,
	FURNACE,
	LADDER,
	RAIL,
	COBBLESTONE_STAIRS,
	LEVER,
	STONE_PRESSURE_PLATE,
	OAK_PRESSURE_PLATE,
	SPRUCE_PRESSURE_PLATE,
	BIRCH_PRESSURE_PLATE,
	JUNGLE_PRESSURE_PLATE,
	ACACIA_PRESSURE_PLATE,
	DARK_OAK_PRESSURE_PLATE,
	CRIMSON_PRESSURE_PLATE,
	WARPED_PRESSURE_PLATE,
	POLISHED_BLACKSTONE_PRESSURE_PLATE,
	REDSTONE_ORE,
	REDSTONE_TORCH,
	REDSTONE_WALL_TORCH,
	SNOW,
	ICE,
	SNOW_BLOCK,
	CACTUS,
	CLAY,
	JUKEBOX,
	OAK_FENCE,
	SPRUCE_FENCE,
	BIRCH_FENCE,
	JUNGLE_FENCE,
	ACACIA_FENCE,
	DARK_OAK_FENCE,
	CRIMSON_FENCE,
	WARPED_FENCE,
	PUMPKIN,
	CARVED_PUMPKIN,
	NETHERRACK,
	SOUL_SAND,
	SOUL_SOIL,
	BASALT,
	POLISHED_BASALT,
	SOUL_TORCH,
	SOUL_WALL_TORCH,
	GLOWSTONE,
	NETHER_PORTAL,
	JACK_O_LANTERN,
	OAK_TRAPDOOR,
	SPRUCE_TRAPDOOR,
	BIRCH_TRAPDOOR,
	JUNGLE_TRAPDOOR,
	ACACIA_TRAPDOOR,
	DARK_OAK_TRAPDOOR,
	CRIMSON_TRAPDOOR,
	WARPED_TRAPDOOR,
	INFESTED_STONE,
	INFESTED_COBBLESTONE,
	INFESTED_STONE_BRICKS,
	INFESTED_MOSSY_STONE_BRICKS,
	INFESTED_CRACKED_STONE_BRICKS,
	INFESTED_CHISELED_STONE_BRICKS,
	STONE_BRICKS,
	MOSSY_STONE_BRICKS,
	CRACKED_STONE_BRICKS,
	CHISELED_STONE_BRICKS,
	BROWN_MUSHROOM_BLOCK,
	RED_MUSHROOM_BLOCK,
	MUSHROOM_STEM,
	IRON_BARS,
	CHAIN,
	GLASS_PANE,
	MELON,
	ATTACHED_MELON_STEM,
	ATTACHED_PUMPKIN_STEM,
	MELON_STEM,
	PUMPKIN_STEM,
	VINE,
	OAK_FENCE_GATE,
	SPRUCE_FENCE_GATE,
	BIRCH_FENCE_GATE,
	JUNGLE_FENCE_GATE,
	ACACIA_FENCE_GATE,
	DARK_OAK_FENCE_GATE,
	CRIMSON_FENCE_GATE,
	WARPED_FENCE_GATE,
	BRICK_STAIRS,
	STONE_BRICK_STAIRS,
	MYCELIUM,
	LILY_PAD,
	NETHER_BRICKS,
	CRACKED_NETHER_BRICKS,
	CHISELED_NETHER_BRICKS,
	NETHER_BRICK_FENCE,
	NETHER_BRICK_STAIRS,
	ENCHANTING_TABLE,
	END_PORTAL_FRAME,
	END_PORTAL,
	END_STONE,
	END_STONE_BRICKS,
	DRAGON_EGG,
	REDSTONE_LAMP,
	COCOA,
	SANDSTONE_STAIRS,
	EMERALD_ORE,
	ENDER_CHEST,
	TRIPWIRE_HOOK,
	TRIPWIRE,
	EMERALD_BLOCK,
	SPRUCE_STAIRS,
	BIRCH_STAIRS,
	JUNGLE_STAIRS,
	CRIMSON_STAIRS,
	WARPED_STAIRS,
	COMMAND_BLOCK,
	BEACON,
	COBBLESTONE_WALL,
	MOSSY_COBBLESTONE_WALL,
	BRICK_WALL,
	PRISMARINE_WALL,
	RED_SANDSTONE_WALL,
	MOSSY_STONE_BRICK_WALL,
	GRANITE_WALL,
	STONE_BRICK_WALL,
	NETHER_BRICK_WALL,
	ANDESITE_WALL,
	RED_NETHER_BRICK_WALL,
	SANDSTONE_WALL,
	END_STONE_BRICK_WALL,
	DIORITE_WALL,
	BLACKSTONE_WALL,
	POLISHED_BLACKSTONE_WALL,
	POLISHED_BLACKSTONE_BRICK_WALL,
	STONE_BUTTON,
	OAK_BUTTON,
	SPRUCE_BUTTON,
	BIRCH_BUTTON,
	JUNGLE_BUTTON,
	ACACIA_BUTTON,
	DARK_OAK_BUTTON,
	CRIMSON_BUTTON,
	WARPED_BUTTON,
	POLISHED_BLACKSTONE_BUTTON,
	ANVIL,
	CHIPPED_ANVIL,
	DAMAGED_ANVIL,
	TRAPPED_CHEST,
	LIGHT_WEIGHTED_PRESSURE_PLATE,
	HEAVY_WEIGHTED_PRESSURE_PLATE,
	DAYLIGHT_DETECTOR,
	REDSTONE_BLOCK,
	NETHER_QUARTZ_ORE,
	HOPPER,
	CHISELED_QUARTZ_BLOCK,
	QUARTZ_BLOCK,
	QUARTZ_BRICKS,
	QUARTZ_PILLAR,
	QUARTZ_STAIRS,
	ACTIVATOR_RAIL,
	DROPPER,
	WHITE_TERRACOTTA,
	ORANGE_TERRACOTTA,
	MAGENTA_TERRACOTTA,
	LIGHT_BLUE_TERRACOTTA,
	YELLOW_TERRACOTTA,
	LIME_TERRACOTTA,
	PINK_TERRACOTTA,
	GRAY_TERRACOTTA,
	LIGHT_GRAY_TERRACOTTA,
	CYAN_TERRACOTTA,
	PURPLE_TERRACOTTA,
	BLUE_TERRACOTTA,
	BROWN_TERRACOTTA,
	GREEN_TERRACOTTA,
	RED_TERRACOTTA,
	BLACK_TERRACOTTA,
	BARRIER,
	IRON_TRAPDOOR,
	HAY_BLOCK,
	WHITE_CARPET,
	ORANGE_CARPET,
	MAGENTA_CARPET,
	LIGHT_BLUE_CARPET,
	YELLOW_CARPET,
	LIME_CARPET,
	PINK_CARPET,
	GRAY_CARPET,
	LIGHT_GRAY_CARPET,
	CYAN_CARPET,
	PURPLE_CARPET,
	BLUE_CARPET,
	BROWN_CARPET,
	GREEN_CARPET,
	RED_CARPET,
	BLACK_CARPET,
	TERRACOTTA,
	COAL_BLOCK,
	PACKED_ICE,
	ACACIA_STAIRS,
	DARK_OAK_STAIRS,
	SLIME_BLOCK,
	GRASS_PATH,
	SUNFLOWER,
	LILAC,
	ROSE_BUSH,
	PEONY,
	TALL_GRASS,
	LARGE_FERN,
	WHITE_STAINED_GLASS,
	ORANGE_STAINED_GLASS,
	MAGENTA_STAINED_GLASS,
	LIGHT_BLUE_STAINED_GLASS,
	YELLOW_STAINED_GLASS,
	LIME_STAINED_GLASS,
	PINK_STAINED_GLASS,
	GRAY_STAINED_GLASS,
	LIGHT_GRAY_STAINED_GLASS,
	CYAN_STAINED_GLASS,
	PURPLE_STAINED_GLASS,
	BLUE_STAINED_GLASS,
	BROWN_STAINED_GLASS,
	GREEN_STAINED_GLASS,
	RED_STAINED_GLASS,
	BLACK_STAINED_GLASS,
	WHITE_STAINED_GLASS_PANE,
	ORANGE_STAINED_GLASS_PANE,
	MAGENTA_STAINED_GLASS_PANE,
	LIGHT_BLUE_STAINED_GLASS_PANE,
	YELLOW_STAINED_GLASS_PANE,
	LIME_STAINED_GLASS_PANE,
	PINK_STAINED_GLASS_PANE,
	GRAY_STAINED_GLASS_PANE,
	LIGHT_GRAY_STAINED_GLASS_PANE,
	CYAN_STAINED_GLASS_PANE,
	PURPLE_STAINED_GLASS_PANE,
	BLUE_STAINED_GLASS_PANE,
	BROWN_STAINED_GLASS_PANE,
	GREEN_STAINED_GLASS_PANE,
	RED_STAINED_GLASS_PANE,
	BLACK_STAINED_GLASS_PANE,
	PRISMARINE,
	PRISMARINE_BRICKS,
	DARK_PRISMARINE,
	PRISMARINE_STAIRS,
	PRISMARINE_BRICK_STAIRS,
	DARK_PRISMARINE_STAIRS,
	SEA_LANTERN,
	RED_SANDSTONE,
	CHISELLED_RED_SANDSTONE,
	CUT_RED_SANDSTONE,
	RED_SANDSTONE_STAIRS,
	REPEATING_COMMAND_BLOCK,
	CHAIN_COMMAND_BLOCK,
	MAGMA_BLOCK,
	NETHER_WART_BLOCK,
	WARPED_WART_BLOCK,
	RED_NETHER_BRICKS,
	BONE_BLOCK,
	STRUCTURE_VOID,
	OBSERVER,
	SHULKER_BOX,
	WHITE_SHULKER_BOX,
	ORANGE_SHULKER_BOX,
	MAGENTA_SHULKER_BOX,
	LIGHT_BLUE_SHULKER_BOX,
	YELLOW_SHULKER_BOX,
	LIME_SHULKER_BOX,
	PINK_SHULKER_BOX,
	GRAY_SHULKER_BOX,
	LIGHT_GRAY_SHULKER_BOX,
	CYAN_SHULKER_BOX,
	PURPLE_SHULKER_BOX,
	BLUE_SHULKER_BOX,
	BROWN_SHULKER_BOX,
	GREEN_SHULKER_BOX,
	RED_SHULKER_BOX,
	BLACK_SHULKER_BOX,
	WHITE_GLAZED_TERRACOTTA,
	ORANGE_GLAZED_TERRACOTTA,
	MAGENTA_GLAZED_TERRACOTTA,
	LIGHT_BLUE_GLAZED_TERRACOTTA,
	YELLOW_GLAZED_TERRACOTTA,
	LIME_GLAZED_TERRACOTTA,
	PINK_GLAZED_TERRACOTTA,
	GRAY_GLAZED_TERRACOTTA,
	LIGHT_GRAY_GLAZED_TERRACOTTA,
	CYAN_GLAZED_TERRACOTTA,
	PURPLE_GLAZED_TERRACOTTA,
	BLUE_GLAZED_TERRACOTTA,
	BROWN_GLAZED_TERRACOTTA,
	GREEN_GLAZED_TERRACOTTA,
	RED_GLAZED_TERRACOTTA,
	BLACK_GLAZED_TERRACOTTA,
	WHITE_CONCRETE,
	ORANGE_CONCRETE,
	MAGENTA_CONCRETE,
	LIGHT_BLUE_CONCRETE,
	YELLOW_CONCRETE,
	LIME_CONCRETE,
	PINK_CONCRETE,
	GRAY_CONCRETE,
	LIGHT_GRAY_CONCRETE,
	CYAN_CONCRETE,
	PURPLE_CONCRETE,
	BLUE_CONCRETE,
	BROWN_CONCRETE,
	GREEN_CONCRETE,
	RED_CONCRETE,
	BLACK_CONCRETE,
	WHITE_CONCRETE_POWDER,
	ORANGE_CONCRETE_POWDER,
	MAGENTA_CONCRETE_POWDER,
	LIGHT_BLUE_CONCRETE_POWDER,
	YELLOW_CONCRETE_POWDER,
	LIME_CONCRETE_POWDER,
	PINK_CONCRETE_POWDER,
	GRAY_CONCRETE_POWDER,
	LIGHT_GRAY_CONCRETE_POWDER,
	CYAN_CONCRETE_POWDER,
	PURPLE_CONCRETE_POWDER,
	BLUE_CONCRETE_POWDER,
	BROWN_CONCRETE_POWDER,
	GREEN_CONCRETE_POWDER,
	RED_CONCRETE_POWDER,
	BLACK_CONCRETE_POWDER,
	TURTLE_EGG,
	DEAD_TUBE_CORAL_BLOCK,
	DEAD_BRAIN_CORAL_BLOCK,
	DEAD_BUBBLE_CORAL_BLOCK,
	DEAD_FIRE_CORAL_BLOCK,
	DEAD_HORN_CORAL_BLOCK,
	TUBE_CORAL_BLOCK,
	BRAIN_CORAL_BLOCK,
	BUBBLE_CORAL_BLOCK,
	FIRE_CORAL_BLOCK,
	HORN_CORAL_BLOCK,
	TUBE_CORAL,
	BRAIN_CORAL,
	BUBBLE_CORAL,
	FIRE_CORAL,
	HORN_CORAL,
	DEAD_BRAIN_CORAL,
	DEAD_BUBBLE_CORAL,
	DEAD_FIRE_CORAL,
	DEAD_HORN_CORAL,
	DEAD_TUBE_CORAL,
	TUBE_CORAL_FAN,
	BRAIN_CORAL_FAN,
	BUBBLE_CORAL_FAN,
	FIRE_CORAL_FAN,
	HORN_CORAL_FAN,
	DEAD_TUBE_CORAL_FAN,
	DEAD_BRAIN_CORAL_FAN,
	DEAD_BUBBLE_CORAL_FAN,
	DEAD_FIRE_CORAL_FAN,
	DEAD_HORN_CORAL_FAN,
	BLUE_ICE,
	CONDUIT,
	POLISHED_GRANITE_STAIRS,
	SMOOTH_RED_SANDSTONE_STAIRS,
	MOSSY_STONE_BRICK_STAIRS,
	POLISHED_DIORITE_STAIRS,
	MOSSY_COBBLESTONE_STAIRS,
	END_STONE_BRICK_STAIRS,
	STONE_STAIRS,
	SMOOTH_SANDSTONE_STAIRS,
	SMOOTH_QUARTZ_STAIRS,
	GRANITE_STAIRS,
	ANDESITE_STAIRS,
	RED_NETHER_BRICK_STAIRS,
	POLISHED_ANDESITE_STAIRS,
	DIORITE_STAIRS,
	POLISHED_GRANITE_SLAB,
	SMOOTH_RED_SANDSTONE_SLAB,
	MOSSY_STONE_BRICK_SLAB,
	POLISHED_DIORITE_SLAB,
	MOSSY_COBBLESTONE_SLAB,
	END_STONE_BRICK_SLAB,
	SMOOTH_SANDSTONE_SLAB,
	SMOOTH_QUARTZ_SLAB,
	GRANITE_SLAB,
	ANDESITE_SLAB,
	RED_NETHER_BRICK_SLAB,
	POLISHED_ANDESITE_SLAB,
	DIORITE_SLAB,
	SCAFFOLDING,
	IRON_DOOR,
	OAK_DOOR,
	SPRUCE_DOOR,
	BIRCH_DOOR,
	JUNGLE_DOOR,
	ACACIA_DOOR,
	DARK_OAK_DOOR,
	CRIMSON_DOOR,
	WARPED_DOOR,
	REPEATER,
	COMPARATOR,
	STRUCTURE_BLOCK,
	JIGSAW,
	TURTLE_HELMET,
	SCUTE,
	FLINT_AND_STEEL,
	APPLE,
	ARROW,
	COAL,
	CHARCOAL,
	DIAMOND,
	IRON_INGOT,
	GOLD_INGOT,
	NETHERITE_INGOT,
	NETHERITE_SCRAP,
	WOODEN_SWORD,
	WOODEN_SHOVEL,
	WOODEN_PICKAXE,
	WOODEN_AXE,
	WOODEN_HOE,
	STONE_SWORD,
	STONE_SHOVEL,
	STONE_PICKAXE,
	STONE_AXE,
	STONE_HOE,
	GOLDEN_SWORD,
	GOLDEN_SHOVEL,
	GOLDEN_PICKAXE,
	GOLDEN_AXE,
	GOLDEN_HOE,
	IRON_SWORD,
	IRON_SHOVEL,
	IRON_PIKAXE,
	IRON_AXE,
	IRON_HOE,
	DIAMOND_SWORD,
	DIAMOND_SHOVEL,
	DIAMOND_PICKAXE,
	DIAMOND_AXE,
	DIAMOND_HOE,
	NETHERITE_SWORD,
	NETHERITE_SHOVEL,
	NETHERITE_PICKAXE,
	NETHERITE_AXE,
	NETHERITE_HOE,
	STICK,
	BOWL,
	MUSHROOM_STEW,
	STRING,
	FEATHER,
	GUN_POWDER,
	WHEAT_SEEDS,
	WHEAT,
	BREAD,
	LEATHER_HELMET,
	LEATHER_CHESTPLATE,
	LEATHER_LEGGINGS,
	LEATHER_BOOTS,
	CHAINMAIL_HELMET,
	CHAINMAIL_CHESTPLATE,
	CHAINMAIL_LEGGINGS,
	CHAINMAIL_BOOTS,
	IRON_HELMET,
	IRON_CHESTPLATE,
	IRON_LEGGINGS,
	IRON_BOOTS,
	DIAMOND_HELMET,
	DIAMOND_CHESTPLATE,
	DIAMOND_LEGGINGS,
	DIAMOND_BOOTS,
	GOLDEN_HELMET,
	GOLDEN_CHESTPLATE,
	GOLDEN_LEGGINGS,
	GOLDEN_BOOTS,
	NETHERITE_HELMET,
	NETHERITE_CHESTPLATE,
	NETHERITE_LEGGINGS,
	NETHERITE_BOOTS,
	FLINT,
	PORKCHOP,
	COOKED_PORKCHOP,
	PAINTING,
	GOLDEN_APPLE,
	ENCHANTED_GOLDEN_APPLE,
	OAK_SIGN,
	SPRUCE_SIGN,
	BIRCH_SIGN,
	JUNGLE_SIGN,
	ACACIA_SIGN,
	DARK_OAK_SIGN,
	CRIMSON_SIGN,
	WARPED_SIGN,
	OAK_WALL_SIGN,
	SPRUCE_WALL_SIGN,
	BIRCH_WALL_SIGN,
	JUNGLE_WALL_SIGN,
	ACACIA_WALL_SIGN,
	DARK_OAK_WALL_SIGN,
	CRIMSON_WALL_SIGN,
	WARPED_WALL_SIGN,
	BUCKET,
	WATER_BUCKET,
	LAVA_BUCKET,
	MINECART,
	SADDLE,
	REDSTONE,
	SNOWBALL,
	OAK_BOAT,
	LEATHER,
	MILK_BUCKET,
	PUFFERFISH_BUCKET,
	SALMON_BUCKET,
	COD_BUCKET,
	TROPICAL_FISH_BUCKET,
	BRICK,
	CLAY_BALL,
	DRIED_KELP_BLOCK,
	PAPER,
	BOOK,
	SLIME_BALL,
	CHEST_MINECART,
	FURNACE_MINECART,
	EGG,
	COMPASS,
	FISHING_ROD,
	CLOCK,
	GLOWSTONE_DUST,
	COD,
	SALMON,
	TROPICAL_FISH,
	PUFFERFISH,
	COOKED_COD,
	COOKED_SALMON,
	INK_SAC,
	COCOA_BEANS,
	LAPIS_LAZULI,
	WHITE_DYE,
	ORANGE_DYE,
	MAGENTA_DYE,
	LIGHT_BLUE_DYE,
	YELLOW_DYE,
	LIME_DYE,
	PINK_DYE,
	GRAY_DYE,
	LIGHT_GRAY_DYE,
	CYAN_DYE,
	PURPLE_DYE,
	BLUE_DYE,
	BROWN_DYE,
	GREEN_DYE,
	RED_DYE,
	BLACK_DYE,
	BONE_MEAL,
	BONE,
	SUGAR,
	CAKE,
	WHITE_BED,
	ORANGE_BED,
	MAGENTA_BED,
	LIGHT_BLUE_BED,
	YELLOW_BED,
	LIME_BED,
	PINK_BED,
	GRAY_BED,
	LIGHT_GRAY_BED,
	CYAN_BED,
	PURPLE_BED,
	BLUE_BED,
	BROWN_BED,
	GREEN_BED,
	RED_BED,
	BLACK_BED,
	COOKIE,
	FILLED_MAP,
	SHEARS,
	MELON_SLICE,
	DRIED_KELP,
	PUMPKIN_SEED,
	MELON_SEEDS,
	BEEF,
	COOKED_BEEF,
	CHICKEN,
	COOKED_CHICKEN,
	ROTTEN_FLESH,
	ENDER_PEARL,
	BLAZE_ROD,
	GHAST_TEAR,
	GOLD_NUGGET,
	NETHER_WART,
	POTION,
	GLASS_BOTTLE,
	SPIDER_EYE,
	FERMENTED_SPIDER_EYE,
	BLAZE_POWDER,
	MAGMA_CREAM,
	BREWING_STAND,
	CAULDRON,
	ENDER_EYE,
	GLISTERING_MELON_SLICE,
	BAT_SPAWN_EGG,
	BEE_SPAWN_EGG,
	BLAZE_SPAWN_EGG,
	CAT_SPAWN_EGG,
	CAVE_SPIDER_SPAWN_EGG,
	CHICKEN_SPAWN_EGG,
	COD_SPAWN_EGG,
	COW_SAWN_EGG,
	CREEPER_SPAWN_EGG,
	DOLPHIN_SPAWN_EGG,
	DONKEY_SPAWN_EGG,
	DROWNED_SPAWN_EGG,
	ELDER_GUARDIAN_SPAWN_EGG,
	ENDERMAN_SPAWN_EGG,
	ENDERMITE_SPAWN_EGG,
	EVOKER_SPAWN_EGG,
	FOX_SPAWN_EGG,
	GHAST_SPAWN_EGG,
	GUARDIAN_SPAWN_EGG,
	HOGLIN_SPAWN_EGG,
	HORSE_SPAWN_EGG,
	HUSK_SPAWN_EGG,
	LLAMA_SPAWN_EGG,
	MAGMA_CUBE_SPAWN_EGG,
	MOOSHROOM_SPAWN_EGG,
	MULE_SPAWN_EGG,
	OCELOT_SPAWN_EGG,
	PANDA_SPAWN_EGG,
	PARROT_SPAWN_EGG,
	PHANTOM_SPAWN_EGG,
	PIG_SPAWN_EGG,
	PIGLIN_SPAWN_EGG,
	PIGLIN_BRUTE_SPAWN_EGG,
	PILLAGER_SPAWN_EGG,
	POLAR_BEAR_SPAWN_EGG,
	PUFFERFISH_SPAWN_EGG,
	RABBIT_SPAWN_EGG,
	RAVAGER_SPAWN_EGG,
	SALMON_SPAWN_EGG,
	SHEEP_SPAWN_EGG,
	SHULKER_SPAWN_EGG,
	SILVERFISH_SPAWN_EGG,
	SKELETON_SPAWN_EGG,
	SKELETON_HORSE_SPAWN_EGG,
	SLIME_SPAWN_EGG,
	SPIDER_SPAWN_EGG,
	SQUID_SPAWN_EGG,
	STRAY_SPAWN_EGG,
	STRIDER_SPAWN_EGG,
	TRADER_LLAMA_SPAWN_EGG,
	TROPICAL_FISH_SPAWN_EGG,
	TURTLE_SPAWN_EGG,
	VEX_SPAWN_EGG,
	VILLAGER_SPAWN_EGG,
	VINDICATOR_SPAWN_EGG,
	WANDERING_TRADER_SPAWN_EGG,
	WITCH_SPAWN_EGG,
	WITHER_SKELETON_SPAWN_EGG,
	WOLF_SPAWN_EGG,
	ZOGLIN_SPAWN_EGG,
	ZOMBIE_SPAWN_EGG,
	ZOMBIE_VILLAGER_SPAWN_EGG,
	ZOMBIEFIED_PIG_SPAWN_EGG,
	EXPERIENCE_BOTTLE,
	FIRE_CHARGE,
	WRITEABLE_BOOK,
	WRITTEN_BOOK,
	EMERALD,
	ITEM_FRAME,
	FLOWER_POT,
	POTTET_OAK_SAPLING,
	POTTET_SPRUCE_SAPLING,
	POTTET_BIRCH_SAPLING,
	POTTET_JUNGLE_SAPLING,
	POTTET_ACACIA_SAPLING,
	POTTET_DARK_OAK_SAPLING,
	POTTET_FERN,
	POTTET_DANDELION,
	POTTET_POPPY,
	POTTET_BLUE_ORCHID,
	POTTET_ALLIUM,
	POTTET_AZURE_BLUET,
	POTTET_RED_TULIP,
	POTTET_ORANGE_TULIP,
	POTTET_WHITE_TULIP,
	POTTET_PINK_TULIP,
	POTTET_OXEYE_DAISY,
	POTTET_CORNFLOWER,
	POTTET_LILY_OF_THE_VALLEY,
	POTTET_WITHER_ROSE,
	POTTET_RED_MUSHROOM,
	POTTET_BROWN_MUSHROOM,
	POTTET_DEAD_BUSH,
	POTTET_CACTUS,
	CARROT,
	CARROTS,
	POTATO,
	POTATOES,
	BAKED_POTATO,
	POISONOUS_POTATO,
	MAP,
	GOLDEN_CARROT,
	SKELETON_SKULL,
	SKELETON_WALL_SKULL,
	WITHER_SKELETON_SKULL,
	WITHER_SKELETON_WALL_SKULL,
	PLAYER_HEAD,
	PLAYER_WALL_HEAD,
	ZOMBIE_HEAD,
	ZOMBIE_WALL_HEAD,
	CREEPER_HEAD,
	CREEPER_WALL_HEAD,
	DRAGON_HEAD,
	DRAGON_WALL_HEAD,
	CARROT_ON_A_STICK,
	WARPED_FUNGUS_ON_A_STICK,
	NETHER_STAR,
	PUMPKIN_PIE,
	FIREWORK_ROCKET,
	FIREWORK_STAR,
	ENCHANTED_BOOK,
	NETHER_BRICK,
	QUARTZ,
	TNT_MINECART,
	HOPPER_MINECART,
	PRISMARINE_SHARD,
	PRISMARINE_CRYSTALS,
	RABBIT,
	COOKED_RABBIT,
	RABBIT_STEW,
	RABBIT_FOOT,
	RABBIT_HIDE,
	ARMOR_STAND,
	IRON_HORSE_ARMOR,
	GOLDEN_HORSE_ARMOR,
	DIAMOND_HORSE_ARMOR,
	LEAD,
	NAME_TAG,
	COMMAND_BLOCK_MINECART,
	MUTTON,
	COOKED_MUTTON,
	WHITE_BANNER,
	ORANGE_BANNER,
	MAGENTA_BANNER,
	LIGHT_BLUE_BANNER,
	YELLOW_BANNER,
	LIME_BANNER,
	PINK_BANNER,
	GRAY_BANNER,
	LIGHT_GRAY_BANNER,
	CYAN_BANNER,
	PURPLE_BANNER,
	BLUE_BANNER,
	BROWN_BANNER,
	GREEN_BANNER,
	RED_BANNER,
	BLACK_BANNER,
	END_CRYSTAL,
	CHORUS_FRUIT,
	POPPED_CHORUS_FRUIT,
	BEETROOT,
	BEETROOT_SOUP,
	DRAGON_BREATH,
	SPLASH_POTION,
	SPECTRAL_ARROW,
	TIPPED_ARROW,
	LINGERING_POTION,
	SHIELD,
	ELYTRA,
	SPRUCE_BOAT,
	BIRCH_BOAT,
	JUNGLE_BOAT,
	ACACIA_BOAT,
	DARK_OAK_BOAT,
	TOTEM_OF_UNDYING,
	SHULKER_SHELL,
	IRON_NUGGET,
	KNOWLEDGE_BOOK,
	DEBUG_STICK,
	MUSIC_DISC_13,
	MUSIC_DISC_CAT,
	MUSIC_DISC_BLOCKS,
	MUSIC_DISC_CHIRP,
	MUSIC_DISC_FAR,
	MUSIC_DISC_MALL,
	MUSIC_DISC_STAL,
	MUSIC_DISC_STRAD,
	MUSIC_DISC_WARD,
	MUSIC_DISC_11,
	MUSIC_DISC_WAIT,
	MUSIC_DISC_PIGSTEP,
	TRIDENT,
	PHANTOM_MEMBRANE,
	NAUTILUS_SHELL,
	HEART_OF_THE_SEA,
	CROSSBOW,
	SUSPICIOUS_STEW,
	LOOM,
	FLOWER_BANNER_PATTERN,
	CREEPER_BANNER_PATTERN,
	SKULL_BANNER_PATTERN,
	MOJANG_BANNER_PATTERN,
	GLOBE_BANNER_PATTERN,
	PIGLIN_BANNER_PATTERN,
	COMPOSTER,
	BARREL,
	SMOKER,
	BlAST_FURNACE,
	CARTOGRAPHY_TABLE,
	FLETCHING_TABLE,
	GRINDSTONE,
	LECTERN,
	SMITHING_TABLE,
	STONECUTTER,
	BELL,
	LANTERN,
	SOUL_LANTERN,
	SWEET_BERRIES,
	CAMPFIRE,
	SOUL_CAMPFIRE,
	SHROOMLIGHT,
	HONEYCOMB,
	BEE_NEST,
	BEEHIVE,
	HONEY_BOTTLE,
	HONEY_BLOCK,
	HONEYCOMB_BLOCK,
	LODESTONE,
	NETHERITE_BLOCK,
	ANCIENT_DEBRIS,
	TARGET,
	CRYING_OBSIDIAN,
	BLACKSTONE,
	BLACKSTONE_SLAB,
	BLACKSTONE_STAIRS,
	GILDED_BLACKSTONE,
	POLISHED_BLACKSTONE,
	POLISHED_BLACKSTONE_SLAB,
	POLISHED_BLACKSTONE_STAIRS,
	CHISELED_POLISHED_BLACKSTONE,
	POLISHED_BLACKSTONE_BRICKS,
	POLISHED_BLACKSTONE_BRICK_SLAB,
	POLISHED_BLACKSTONE_BRICK_STAIRS,
	CRACKED_POLISHED_BLACKSTONE_BRICKS,
	RESPAWN_ANCHOR;
	
	
	
	
	
	static {
		BY_NAME = new HashMap<String, Material>();
		META_FACTORYS = new HashMap<Material, MetaDataFactory>();
		MetaDataFactory SNOWABLE_MDF = new ClassMetaDataFactory(Snowable.class, null),
		SAPLING_MDF = new ClassMetaDataFactory(Sapling.class, null),
		LEVELLED_MDF = new ClassMetaDataFactory(Levelled.class, null),
		ORIENTABLE_MDF = new ClassMetaDataFactory(Orientable.class, null),
		LEAVES = new ClassMetaDataFactory(Leaves.class, null),
		DISPENSER_MDF = new ClassMetaDataFactory(Dispenser.class, null),
		NOTE_BLOCK_MDF = new ClassMetaDataFactory(NoteBlock.class, null),
		BED_MDF = new ClassMetaDataFactory(Bed.class, null),
		REDSTONE_RAIL_MDF = new ClassMetaDataFactory(RedstoneRail.class, null),
		PISTION_MDF = new ClassMetaDataFactory(Pistion.class, null),
		BISECTED_MDF = new ClassMetaDataFactory(Bisected.class, null),
		PISTION_HEAD_MDF = new ClassMetaDataFactory(null, null, PistionHead.class, null),
		TECHNICAL_PISTION_MDF = new ClassMetaDataFactory(null, null, TechnicalPistion.class, null),
		TNT_MDF = new ClassMetaDataFactory(de.atlasmc.block.data.TNT.class, null),
		DIRECTIONAL_MDF = new ClassMetaDataFactory(Directional.class, null),
		FIRE_MDF = new ClassMetaDataFactory(null, null, Fire.class, null),
		STAIRS_MDF = new ClassMetaDataFactory(Stairs.class, null),
		CHEST_MDF = new ClassMetaDataFactory(Chest.class, null),
		REDSTONE_WIRE_MDF = new ClassMetaDataFactory(null, null, RedstoneWire.class, null),
		AGEABLE_MDF = new ClassMetaDataFactory(Ageable.class, null),
		FARMLAND_MDF = new ClassMetaDataFactory(Farmland.class, null),
		FURNACE_MDF = new ClassMetaDataFactory(Furnace.class, null),
		SIGN_MDF = new ClassMetaDataFactory(Sign.class, null),
		DOOR_MDF = new ClassMetaDataFactory(Door.class, null),
		LADDER_MDF = new ClassMetaDataFactory(Ladder.class, null),
		RAIL_MDF = new ClassMetaDataFactory(Rail.class, null),
		WALL_SIGN_MDF = new ClassMetaDataFactory(WallSign.class, null),
		SWITCH_MDF = new ClassMetaDataFactory(Switch.class, null),
		POWERABLE_MDF = new ClassMetaDataFactory(Powerable.class, null),
		LIGHTABLE_MDF = new ClassMetaDataFactory(Lightable.class, null),
		RED_WALL_TORCH_MDF = new ClassMetaDataFactory(RedstoneWallTorch.class, null),
		SNOW_MDF = new ClassMetaDataFactory(Snow.class, null),
		JUKEBOX_MDF = new ClassMetaDataFactory(Jukebox.class, null),
		FENCE_MDF = new ClassMetaDataFactory(Fence.class, null),
		CAKE_MDF = new ClassMetaDataFactory(Cake.class, null),
		REPEATER_MDF = new ClassMetaDataFactory(Repeater.class, null),
		TRAPDOOR_MDF = new ClassMetaDataFactory(TrapDoor.class, null),
		MULTIPLE_FACING_MDF = new ClassMetaDataFactory(MultipleFacing.class, null),
		CHAIN_MDF = new ClassMetaDataFactory(Chain.class, null),
		GATE_MDF = new ClassMetaDataFactory(Gate.class, null),
		BREWING_STAND_MDF = new ClassMetaDataFactory(BrewingStand.class, null),
		END_PORTAL_FRAME_MDF = new ClassMetaDataFactory(EndPortalFrame.class, null),
		COCOA_MDF = new ClassMetaDataFactory(Cocoa.class, null),
		ENDER_CHEST_MDF = new ClassMetaDataFactory(EnderChest.class, null),
		TRIPWIRE_HOOK_MDF = new ClassMetaDataFactory(TripwireHook.class, null),
		TRIPWIRE_MDF = new ClassMetaDataFactory(Tripwire.class, null),
		COMMAND_BLOCK_MDF = new ClassMetaDataFactory(CommandBlock.class, null),
		WALL_MDF = new ClassMetaDataFactory(Wall.class, null),
		ROTATABLE_MDF = new ClassMetaDataFactory(Rotatable.class, null),
		ANALOGUE_POWERABLE_MDF = new ClassMetaDataFactory(AnaloguePowerable.class, null),
		COMPARATOR_MDF = new ClassMetaDataFactory(Comparator.class, null),
		DAYLIGHT_DETECTORE_MDF = new ClassMetaDataFactory(DaylightDetectore.class, null),
		HOPPER_MDF = new ClassMetaDataFactory(Hopper.class, null);
		
		AIR = c("AIR", 0, new ClassMetaDataFactory(null, null, null, null));
		STONE = c("STONE", 1);
		GRANITE = c("GRANITE", 2);
		POLISHED_GRANITE = c("POLISHED_GRANITE", 3);
		DIORITE = c("DIORITE", 4);
		POLISHED_DIORITE = c("POLISHED_DIORITE", 5);
		ANDESITE = c("ANDESITE", 6);
		POLISHED_ANDESITE = c("POLISHED_ANDESITE", 7);
		GRASS_BLOCK = c("GRASS_BLOCK", 8, SNOWABLE_MDF);
		DIRT = c("DIRT", 10);
		COARSE_DIRT = c("COARSE_DIRT", 11);
		PODZOL = c("PODZOL", 12, SNOWABLE_MDF);
		CRIMSON_NYLIUM = null;
		WARPED_NYLIUM = null;
		COBBLESTONE = c("COBBLESTONE", 14);
		OAK_PLANKS = c("OAK_PLANKS", 15);
		SPRUCE_PLANKS = c("SPRUCE_PLANKS", 16);
		BIRCH_PLANKS = c("BIRCH_PLANKS", 17);
		JUNGLE_PLANKS = c("JUNGLE_PLANKS", 18);
		ACACIA_PLANKS = c("ACACIA_PLANKS", 19);
		DARK_OAK_PLANKS = c("DARK_OAK_PLANKS", 20);
		CRIMSON_PLANKS = null;
		WARPED_PLANKS = null;
		OAK_SAPLING = c("OAK_SAPLING", 21, SAPLING_MDF);
		SPRUCE_SAPLING = c("SPRUCE_SAPLING", 23, SAPLING_MDF);
		BIRCH_SAPLING = c("BIRCH_SAPLING", 25, SAPLING_MDF);
		JUNGLE_SAPLING = c("JUNGLE_SAPLING", 27, SAPLING_MDF);
		ACACIA_SAPLING = c("ACACIA_SAPLING", 29, SAPLING_MDF);
		DARK_OAK_SAPLING = c("DARK_OAK_SAPLING", 31, SAPLING_MDF);
		BEDROCK = c("BEDROCK", 33);
		WATER = new Material("WATER", false, (short) 34, LEVELLED_MDF);
		LAVA = new Material("LAVA", (short) 50, LEVELLED_MDF);
		SAND = c("SAND", 66);
		RED_SAND = c("RED_SAND", 67);
		GRAVEL = c("GRAVEL", 68);
		GOLD_ORE = c("GOLD_ORE", 69);
		IRON_ORE = c("IRON_ORE", 70);
		COAL_ORE = c("COAL_ORE", 71);
		NETHER_GOLD_ORE = c("NETHER_GOLD_ORE", 72);
		OAK_LOG = c("OAK_LOG", 73, ORIENTABLE_MDF);
		SPRUCE_LOG = c("SPRUCE_LOG", 76, ORIENTABLE_MDF);
		BIRCH_LOG = c("BIRCH_LOG", 79, ORIENTABLE_MDF);
		JUNGLE_LOG = c("JUNGLE_LOG", 82, ORIENTABLE_MDF);
		ACACIA_LOG = c("ACACIA_LOG", 85, ORIENTABLE_MDF);
		DARK_OAK_LOG = c("DARK_OAK_LOG", 88, ORIENTABLE_MDF);
		CRIMSON_STEM = null;
		WARPED_STEM = null;
		STRIPPED_OAK_LOG = c("STRIPPED_OAK_LOG", 106, ORIENTABLE_MDF);
		STRIPPED_SPRUCE_LOG = c("STRIPPED_SPRUCE_LOG", 91, ORIENTABLE_MDF);
		STRIPPED_BIRCH_LOG = c("STRIPPED_BIRCH_LOG", 94, ORIENTABLE_MDF);
		STRIPPED_JUNGLE_LOG = c("STRIPPED_JUNGLE_LOG", 97, ORIENTABLE_MDF);
		STRIPPED_ACACIA_LOG = c("STRIPPED_ACACIA_LOG", 100, ORIENTABLE_MDF);
		STRIPPED_DARK_OAK_LOG = c("STRIPPED_DARK_OAK_LOG", 103, ORIENTABLE_MDF);
		STRIPPED_CRIMSON_STEM = null;
		STRIPPED_WARPED_STEM = null;
		STRIPPED_OAK_WOOD = c("STRIPPED_OAK_WOOD", 127, ORIENTABLE_MDF);
		STRIPPED_SPRUCE_WOOD = c("STRIPPED_SPRUCE_WOOD", 130, ORIENTABLE_MDF);
		STRIPPED_BIRCH_WOOD = c("STRIPPED_BIRCH_WOOD", 133, ORIENTABLE_MDF);
		STRIPPED_JUNGLE_WOOD = c("STRIPPED_JUNGLE_WOOD", 136, ORIENTABLE_MDF);
		STRIPPED_ACACIA_WOOD = c("STRIPPED_ACACIA_WOOD", 139, ORIENTABLE_MDF);
		STRIPPED_DARK_OAK_WOOD = c("STRIPPED_DARK_OAK_WOOD", 142, ORIENTABLE_MDF);
		STRIPPED_CRIMSON_HYPHAE = null;
		STRIPPED_WARPED_HYPHAE = null;
		OAK_WOOD = c("OAK_WOOD", 109, ORIENTABLE_MDF);
		SPRUCE_WOOD = c("SPRUCE_WOOD", 112, ORIENTABLE_MDF);
		BIRCH_WOOD = c("BIRCH_WOOD", 115, ORIENTABLE_MDF);
		JUNGLE_WOOD = c("JUNGLE_WOOD", 118, ORIENTABLE_MDF);
		ACACIA_WOOD = c("ACACIA_WOOD", 121,  ORIENTABLE_MDF);
		DARK_OAK_WOOD = c("DARK_OAK_WOOD", 124, ORIENTABLE_MDF);
		CRIMSON_HYPHAE = null;
		WARPED_HYPHAE = null;
		OAK_LEAVES = c("OAK_LEAVES", 145, LEAVES);
		SPRUCE_LEAVES = c("SPRUCE_LEAVES", 159, LEAVES);
		BIRCH_LEAVES = c("BIRCH_LEAVES", 173, LEAVES);
		JUNGLE_LEAVES = c("JUNGLE_LEAVES", 187, LEAVES);
		ACACIA_LEAVES = c("ACACIA_LEAVES", 201, LEAVES);
		DARK_OAK_LEAVES = c("DARK_OAK_LEAVES", 215, LEAVES);
		SPONGE = c("SPONGE", 229);
		WET_SPONGE = c("WET_SPONGE", 230);
		GLASS = c("GLASS", 231);
		LAPIS_ORE = c("LAPIS_ORE", 232);
		LAPIS_BLOCK = c("LAPIS_BLOCK", 233);
		DISPENSER = c("DISPENSER", 234, DISPENSER_MDF);
		SANDSTONE = c("SANDSTONE", 246);
		CHISELED_SANDSTONE = c("CHISELED_SANDSTONE", 247);
		CUT_SANDSTONE = c("CUT_SANDSTONE", 248);
		NOTE_BLOCK = c("NOTE_BLOCK", 249, NOTE_BLOCK_MDF);
		POWERED_RAIL = c("POWERED_RAIL", 1305, REDSTONE_RAIL_MDF);
		DETECTOR_RAIL = c("DETECTOR_RAIL", 1317, REDSTONE_RAIL_MDF);
		STICKY_PISTION = c("STICKY_PISTION", 1329, PISTION_MDF);
		COBWEB = c("COBWEB", 1341);
		GRASS = c("GRASS", 1342);
		FERN = c("FERB", 1343);
		DEAD_BUSH = c("DEAD_BUSH", 1344);
		SEAGRASS = c("SEAGRASS", 1345);
		TALL_SEAGRASS = new Material("TALL_SEAGRASS", false, (short) 1346, BISECTED_MDF);
		SEA_PICKLE = null;
		PISTION = c("PISTION", 1348, PISTION_MDF);
		PISTION_HEAD = new Material("PISTION_HEAD", false, (short) 1360, PISTION_HEAD_MDF);
		MOVING_PISTION = new Material("MOVING_PISTION", false, (short) 1400, TECHNICAL_PISTION_MDF);
		WHITE_WOOL = c("WHITE_WOOL", 1384);
		ORANGE_WOOL = c("ORANGE_WOOL", 1385);
		MAGENTA_WOOL = c("MAGENTA_WOOL", 1386);
		LIGHT_BLUE_WOOL = c("LIGHT_BLUE_WOOL", 1387);
		YELLOW_WOOL = c("YELLOW_WOOL", 1388);
		LIME_WOOL = c("LIME_WOOL", 1389);
		PINK_WOOL = c("PINK_WOOL", 1390);
		GRAY_WOOL = c("GRAY_WOOL", 1391);
		LIGHT_GRAY_WOOL = c("LIGHT_GRAY", 1392);
		CYAN_WOOL = c("CYAN_WOOL", 1393);
		PURPLE_WOOL = c("PURPLE_WOOL", 1394);
		BLUE_WOOL = c("BLUE_WOOL", 1395);
		BROWN_WOOL = c("BROWN_WOOL", 1396);
		GREEN_WOOL = c("GREEN_WOOL", 1397);
		RED_WOOL = c("RED_WOOL", 1398);
		BLACK_WOOL = c("BLACK_WOOL", 1399);
		DANDELION = c("DANDELION", 1412);
		POPPY = c("POPPY", 1413);
		BLUE_ORCHID = c("BLUE_ORCHID", 1414);
		ALLIUM = c("ALLIUM", 1415);
		AZURE_BLUET = c("AZURE_BLUET", 1416);
		RED_TULIP = c("RED_TULIP", 1417);
		ORANGE_TULIP = c("ORANGE_TULIP", 1418);
		WHITE_TULIP = c("WHITE_TULIP", 1419);
		PINK_TULIP = c("PINK_TULIP", 1420);
		OXEYE_DAISY = c("OXEYE_DAISY", 1421);
		CORNFLOWER = c("CORNFLOWER", 1422);
		LILY_OF_THE_VALLEY = c("LILY_OF_THE_VALLEY", 1424);
		WITHER_ROSE = c("WITHER_ROSE", 1423);
		BROWN_MUSHROOM = c("BROWN_MUSHROOM", 1425);
		RED_MUSHROOM = c("RED_MUSHROOM", 1426);
		CRIMSON_FUNGUS,
		WARPED_FUNGUS,
		CRIMSON_ROOTS,
		WARPED_ROOTS,
		NETHER_SPROUTS,
		WEEPING_VINES,
		TWISTING_VINES,
		SUGAR_CANE = c("SUGAR_CANE", 3948, AGEABLE_MDF);
		KELP,
		BAMBOO,
		GOLD_BLOCK = c("GOLD_BLOCK", 1427);
		IRON_BLOCK = c("IRON_BLOCK", 1428);
		OAK_SLAB,
		SPRUCE_SLAB,
		BIRCH_SLAB,
		JUNGLE_SLAB,
		ACACIA_SLAB,
		DARK_OAK_SLAB,
		CRIMSON_SLAB,
		WARPED_SLAB,
		STONE_SLAB,
		SMOOTH_STONE_SLAB,
		SANDSTONE_SLAB,
		CUT_SANDSTONE_SLAB,
		PETRIFIED_OAK_SLAB,
		COBBLESTONE_SLAB,
		BRICK_SLAB,
		STONE_BRICK_SLAB,
		NETHER_BRICK_SLAB,
		QUARTZ_SLAB,
		RED_SANDSTONE_SLAB,
		CUT_RED_SANDSTONE_SLAB,
		PURPUR_SLAB,
		PRISMARINE_SLAB,
		PRISMARINE_BRICK_SLAB,
		DARK_PRISMARINE_SLAB,
		SMOOTH_QUARTZ,
		SMOOTH_RED_SANDSTONE,
		SMOOTH_SANDSTONE,
		SMOOTH_STONE,
		BRICKS = c("BRICKS", 1429);
		TNT = c("TNT", 1430, TNT_MDF);
		BOOKSHELF = c("BOOKSHELF", 1432);
		MOSSY_COBBLESTONE = c("MOSSY_COBBLESTONE", 1433);
		OBSIDIAN = c("OBSIDIAN", 1433);
		TORCH = c("TORCH", 1435);
		WALL_TORCH = new Material("WALL_TORCH", false, (short) 1436, DIRECTIONAL_MDF);
		FIRE = new Material("FIRE", false, (short) 1440, FIRE_MDF);
		SOUL_FIRE = new Material("SOUL_FIRE", false, (short) 1952, MetaDataFactory.DEFAULT);
		END_ROD,
		CHORUS_PLANT,
		CHORUS_FLOWER,
		PURPUR_BLOCK,
		PURPUR_PILLAR,
		PURPUR_STAIRS,
		SPAWNER = c("SPAWNER", 1953);
		OAK_STAIRS = c("OAK_STAIRS", 1954, STAIRS_MDF);
		CHEST = c("CHEST", 2034, CHEST_MDF);
		REDSTONE_WIRE = c("RESTONE_WIRE", 2058, REDSTONE_WIRE_MDF);
		DIAMOND_ORE = c("DIAMOND_ORE", 3354);
		DIAMOND_BLOCK = c("DIAMOND_BLOCK", 3355);
		CRAFTING_TABLE = c("CRAFTING_TABLE", 3356);
		FARMLAND = c("FARMLAND", 3365, FARMLAND_MDF);
		FURNACE = c("FURNACE", 3373, FURNACE_MDF);
		LADDER = c("LADDER", 3637, LADDER_MDF);
		RAIL = c("RAIL", 3645, RAIL_MDF);
		COBBLESTONE_STAIRS = c("COBBLESTONE_STAIRS", 3655, STAIRS_MDF);
		LEVER = c("LEVER", 3783, SWITCH_MDF);
		STONE_PRESSURE_PLATE = c("STONE_PRESSURE_PLATE", 3807, POWERABLE_MDF);
		OAK_PRESSURE_PLATE = c("OAK_PRESSURE_PLATE", 3873, POWERABLE_MDF);
		SPRUCE_PRESSURE_PLATE = c("SPRUCE_PRESSURE_PLATE", 3875, POWERABLE_MDF);
		BIRCH_PRESSURE_PLATE = c("BIRCH_PRESSURE_PLATE", 3877, POWERABLE_MDF);
		JUNGLE_PRESSURE_PLATE = c("JUNGLE_PRESSURE_PLATE", 3879, POWERABLE_MDF);
		ACACIA_PRESSURE_PLATE = c("ACACIA_PRESSURE_PLATE", 3881, POWERABLE_MDF);
		DARK_OAK_PRESSURE_PLATE = c("DARK_OAK_PRESSURE_PLATE", 3883, POWERABLE_MDF);
		CRIMSON_PRESSURE_PLATE,
		WARPED_PRESSURE_PLATE,
		POLISHED_BLACKSTONE_PRESSURE_PLATE,
		REDSTONE_ORE = c("REDSTONE_ORE", 3885, LIGHTABLE_MDF);
		REDSTONE_TORCH = c("REDSTONE_TORCH", 3887, LIGHTABLE_MDF);
		REDSTONE_WALL_TORCH = c("REDSTONE_WALL_TORCH", 3889, RED_WALL_TORCH_MDF);
		SNOW = c("SNOW", 3921, SNOW_MDF);
		ICE = c("ICE", 3929);
		SNOW_BLOCK = c("SNOW_BLOCK", 3930);
		CACTUS = c("CACTUS", 3931, AGEABLE_MDF);
		CLAY = c("CLAY", 3947);
		JUKEBOX = c("JUKEBOX", 3964, JUKEBOX_MDF);
		OAK_FENCE = c("OAK_FENCE", 3966, FENCE_MDF);
		SPRUCE_FENCE,
		BIRCH_FENCE,
		JUNGLE_FENCE,
		ACACIA_FENCE,
		DARK_OAK_FENCE,
		CRIMSON_FENCE,
		WARPED_FENCE,
		PUMPKIN = c("PUMPKIN", 3998);
		CARVED_PUMPKIN = c("CARVED_PUMPKIN", 4016, DIRECTIONAL_MDF);
		NETHERRACK = c("NETHERRACK", 3999);
		SOUL_SAND = c("SOUL_SAND", 4000);
		SOUL_SOIL = c("SOUL_SOIL", 4001);
		BASALT = c("BASALT", 4002, ORIENTABLE_MDF);
		POLISHED_BASALT = c("POLISHED_BASALT", 4005, ORIENTABLE_MDF);
		SOUL_TORCH = c("SOUL_TORCH", 4008);
		SOUL_WALL_TORCH = new Material("SOUL_WALL_TORCH", false, (short) 4009, DIRECTIONAL_MDF);
		GLOWSTONE = c("GLOWSTONE", 4013);
		NETHER_PORTAL = new Material("NETHER_PORTAL", false, (short) 4014, ORIENTABLE_MDF);
		JACK_O_LANTERN = c("JACK_O_LANTERN", 4020, DIRECTIONAL_MDF);
		OAK_TRAPDOOR = c("OAK_TRAPDOOR", 4111, TRAPDOOR_MDF);
		SPRUCE_TRAPDOOR = c("SPRUCE_TRAPDOOR", 4175, TRAPDOOR_MDF);
		BIRCH_TRAPDOOR = c("BIRCH_TRAPDOOR", 4239, TRAPDOOR_MDF);
		JUNGLE_TRAPDOOR = c("JUNGLE_TRAPDOOR", 4303, TRAPDOOR_MDF);
		ACACIA_TRAPDOOR = c("ACACIA_TRAPDOOR", 4367, TRAPDOOR_MDF);
		DARK_OAK_TRAPDOOR = c("DARK_OAK_TRAPDOOR", 4431, TRAPDOOR_MDF);
		CRIMSON_TRAPDOOR,
		WARPED_TRAPDOOR,
		INFESTED_STONE = c("INFESTED_STONE", 4499);
		INFESTED_COBBLESTONE = c("INFESTED_COBBLESTONE", 4500);
		INFESTED_STONE_BRICKS = c("INFESTED_STONE_BRICKS", 4501);
		INFESTED_MOSSY_STONE_BRICKS = c("INFESTED_MOSSY_STONE_BRICKS", 4502);
		INFESTED_CRACKED_STONE_BRICKS = c("INFESTED_CRACKED_STONE_BRICKS", 4503);
		INFESTED_CHISELED_STONE_BRICKS = c("INFESTED_CHISELED_STONE_BRICKS", 4504);
		STONE_BRICKS = c("STONE_BRICKS", 4495);
		MOSSY_STONE_BRICKS = c("MOSSY_STONE_BRICKS", 4496);
		CRACKED_STONE_BRICKS = c("CRACKED_STONE_BRICKS", 4497);
		CHISELED_STONE_BRICKS = c("CHISELED_STONE_BRICKS", 4498);
		BROWN_MUSHROOM_BLOCK = c("BROWN_MUSHROOM_BLOCK", 4505, MULTIPLE_FACING_MDF);
		RED_MUSHROOM_BLOCK = c("RED_MUSHROOM_BLOCK", 4569, MULTIPLE_FACING_MDF);
		MUSHROOM_STEM = c("MUSHROOM_STEM", 4633, MULTIPLE_FACING_MDF);
		IRON_BARS = c("IRON_BARS", 4697, FENCE_MDF);
		CHAIN = c("CHAIN", 4729, CHAIN_MDF);
		GLASS_PANE = c("GLASS_PANE", 4735, FENCE_MDF);
		MELON = c("MELON", 4767);
		ATTACHED_MELON_STEM = new Material("ATTACHED_MELON_STEM", false, (short) 4768, DIRECTIONAL_MDF);
		ATTACHED_PUMPKIN_STEM = new Material("ATTACHED_PUMKIN_STEM", false, (short) 4772, DIRECTIONAL_MDF);
		MELON_STEM = new Material("MELON_STEM", false, (short) 4784, AGEABLE_MDF);
		PUMPKIN_STEM = new Material("PUMPKIN_STEM", false, (short) 4776, AGEABLE_MDF);
		VINE = c("VINE", 4792, MULTIPLE_FACING_MDF);
		OAK_FENCE_GATE = c("OAK_FENCE_GATE", 4825, GATE_MDF);
		SPRUCE_FENCE_GATE,
		BIRCH_FENCE_GATE,
		JUNGLE_FENCE_GATE,
		ACACIA_FENCE_GATE,
		DARK_OAK_FENCE_GATE,
		CRIMSON_FENCE_GATE,
		WARPED_FENCE_GATE,
		BRICK_STAIRS = c("BRICK_STAIRS", 4856, STAIRS_MDF);
		STONE_BRICK_STAIRS = c("STONE_BRICK_STAIRS", 4936, STAIRS_MDF);
		MYCELIUM = c("MYCELIUM", 5016, SNOWABLE_MDF);
		LILY_PAD = c("LILY_PAD", 5018);
		NETHER_BRICKS = c("NETHER_BRICKS", 5019);
		CRACKED_NETHER_BRICKS,
		CHISELED_NETHER_BRICKS,
		NETHER_BRICK_FENCE = c("NETHER_BRICK_FENCE", 5020, FENCE_MDF);
		NETHER_BRICK_STAIRS = c("NETHER_BRICK_STAIRS", 5052, STAIRS_MDF);
		ENCHANTING_TABLE = c("ENCHANTING_TABLE", 5136);
		END_PORTAL_FRAME = c("END_PORTAL_FRAME", 5150, END_PORTAL_FRAME_MDF);
		END_PORTAL = c("END_PORTAL", 5149);
		END_STONE = c("END_STONE", 5158);
		END_STONE_BRICKS,
		DRAGON_EGG = c("DRAGON_EGG", 5159);
		REDSTONE_LAMP = c("REDSTONE_LAMP", 5160);
		COCOA = new Material("COCOA", false, (short) 5162, COCOA_MDF);
		SANDSTONE_STAIRS = c("SANDSTONE_STAIRS", 5174, STAIRS_MDF);
		EMERALD_ORE = c("EMERALD_ORE", 5254);
		ENDER_CHEST = c("ENDER_CHEST", 5255, ENDER_CHEST_MDF);
		TRIPWIRE_HOOK = c("TRIPWIRE_HOOK", 5263, TRIPWIRE_HOOK_MDF);
		TRIPWIRE = new Material("TRIPWIRE", false, (short) 5279, TRIPWIRE_MDF);
		EMERALD_BLOCK = c("EMERALD_BLOCK", 5407);
		SPRUCE_STAIRS = c("SPRUCE_STAIRS", 5408, STAIRS_MDF);
		BIRCH_STAIRS = c("BIRCH_STAIRS", 5488, STAIRS_MDF);
		JUNGLE_STAIRS = c("JUNGLE_STAIRS", 5568, STAIRS_MDF);
		CRIMSON_STAIRS,
		WARPED_STAIRS,
		COMMAND_BLOCK = c("COMMAND_BLOCK", 5648, COMMAND_BLOCK_MDF);
		BEACON = c("BEACON", 5660);
		COBBLESTONE_WALL = c("COBBLESTONE_WALL", 5661, WALL_MDF);
		MOSSY_COBBLESTONE_WALL = c("MOSSY_COBBLESTONE_WALL", 5985, WALL_MDF);
		BRICK_WALL,
		PRISMARINE_WALL,
		RED_SANDSTONE_WALL,
		MOSSY_STONE_BRICK_WALL,
		GRANITE_WALL,
		STONE_BRICK_WALL,
		NETHER_BRICK_WALL,
		ANDESITE_WALL,
		RED_NETHER_BRICK_WALL,
		SANDSTONE_WALL,
		END_STONE_BRICK_WALL,
		DIORITE_WALL,
		BLACKSTONE_WALL,
		POLISHED_BLACKSTONE_WALL,
		POLISHED_BLACKSTONE_BRICK_WALL,
		STONE_BUTTON = c("STONE_BUTTON", 3897, SWITCH_MDF);
		OAK_BUTTON = c("OAK_BUTTON", 6350, SWITCH_MDF);
		SPRUCE_BUTTON = c("SPRUCE_BUTTON", 6374, SWITCH_MDF);
		BIRCH_BUTTON = c("BIRCH_BUTTON", 6398, SWITCH_MDF);
		JUNGLE_BUTTON = c("JUNGLE_BUTTON", 6422, SWITCH_MDF);
		ACACIA_BUTTON = c("ACACIA_BUTTON", 6446, SWITCH_MDF);
		DARK_OAK_BUTTON = c("DARK_OAK_BUTTON", 6470, SWITCH_MDF);
		CRIMSON_BUTTON,
		WARPED_BUTTON,
		POLISHED_BLACKSTONE_BUTTON,
		ANVIL = c("ANVIL", 6614, DIRECTIONAL_MDF);
		CHIPPED_ANVIL = c("CHIPPED_ANVIL", 6618, DIRECTIONAL_MDF);
		DAMAGED_ANVIL = c("DAMAGED_ANVIL", 6622, DIRECTIONAL_MDF);
		TRAPPED_CHEST = c("TRAPPED_CHEST", 6626, CHEST_MDF);
		LIGHT_WEIGHTED_PRESSURE_PLATE = c("LIGHT_WEIGHTED_PRESSURE_PLATE", 6650, ANALOGUE_POWERABLE_MDF);
		HEAVY_WEIGHTED_PRESSURE_PLATE = c("HEAVY_WEIGHTED_PRESSURE_PLATE", 6666, ANALOGUE_POWERABLE_MDF);
		DAYLIGHT_DETECTOR = c("DAYLIGHT_DETECTORE", 6698, DAYLIGHT_DETECTORE_MDF);
		REDSTONE_BLOCK = c("REDSTONE_BLOCK", 6730);
		NETHER_QUARTZ_ORE = c("NETHER_QUARTZ_ORE", 6731);
		HOPPER = c("HOPPER", 6732, HOPPER_MDF);
		CHISELED_QUARTZ_BLOCK = c("CHISELED_QUARTZ_BLOCK", 6743);
		QUARTZ_BLOCK = c("QUARTZ_BLOCK", 6742);
		QUARTZ_BRICKS,
		QUARTZ_PILLAR = c("QUARTZ_PILLAR", 6744, ORIENTABLE_MDF);
		QUARTZ_STAIRS = c("QUARTZ_STAIRS", 6747, STAIRS_MDF);
		ACTIVATOR_RAIL = c("ACTIVATOR_RAIL", 6827, REDSTONE_RAIL_MDF);
		DROPPER = c("DROPPER", 6839, DISPENSER_MDF);
		WHITE_TERRACOTTA = c("WHITE_TERRACOTTA", 6851);
		ORANGE_TERRACOTTA = c("ORANGE_TERRACOTTA", 6852);
		MAGENTA_TERRACOTTA = c("MAGENTA_TERRACOTTA", 6853);
		LIGHT_BLUE_TERRACOTTA = c("LIGHT_BLUE_TERRACOTTA", 6854);
		YELLOW_TERRACOTTA = c("YELLOW_TERRACOTTA", 6855);
		LIME_TERRACOTTA = c("LIME_TERRACOTTA", 6856);
		PINK_TERRACOTTA = c("PINK_TERRACOTTA", 6857);
		GRAY_TERRACOTTA = c("GRAY_TERRACOTTA", 6858);
		LIGHT_GRAY_TERRACOTTA = c("LIGHT_GRAY_TERRACOTTA", 6859);
		CYAN_TERRACOTTA = c("CYAN_TERRACOTTA", 6860);
		PURPLE_TERRACOTTA = c("PURPLE_TERRACOTTA", 6861);
		BLUE_TERRACOTTA = c("BLUE_TERRACOTTA", 6862);
		BROWN_TERRACOTTA = c("BROWN_TERRACOTTA", 6863);
		GREEN_TERRACOTTA = c("GREEN_TERRACOTTA", 6864);
		RED_TERRACOTTA = c("RED_TERRACOTTA", 6865);
		BLACK_TERRACOTTA = c("BLACK_TERRACOTTA", 6866);
		BARRIER,
		IRON_TRAPDOOR,
		HAY_BLOCK,
		WHITE_CARPET,
		ORANGE_CARPET,
		MAGENTA_CARPET,
		LIGHT_BLUE_CARPET,
		YELLOW_CARPET,
		LIME_CARPET,
		PINK_CARPET,
		GRAY_CARPET,
		LIGHT_GRAY_CARPET,
		CYAN_CARPET,
		PURPLE_CARPET,
		BLUE_CARPET,
		BROWN_CARPET,
		GREEN_CARPET,
		RED_CARPET,
		BLACK_CARPET,
		TERRACOTTA,
		COAL_BLOCK,
		PACKED_ICE,
		ACACIA_STAIRS,
		DARK_OAK_STAIRS,
		SLIME_BLOCK,
		GRASS_PATH,
		SUNFLOWER,
		LILAC,
		ROSE_BUSH,
		PEONY,
		TALL_GRASS,
		LARGE_FERN,
		WHITE_STAINED_GLASS = c("WHITE_STAINED_GLASS", 4095);
		ORANGE_STAINED_GLASS = c("ORANGE_STAINED_GLASS", 4096);
		MAGENTA_STAINED_GLASS = c("MAGENTA_STAINED_GLASS", 4097);
		LIGHT_BLUE_STAINED_GLASS = c("LIGH_BLUE_STAINED_GLASS", 4098);
		YELLOW_STAINED_GLASS = c("YELLOW_STAINED_GLASS", 4099);
		LIME_STAINED_GLASS = c("LIME_STAINED_GLASS", 4100);
		PINK_STAINED_GLASS = c("PINK_STAINED_GLASS", 4101);
		GRAY_STAINED_GLASS = c("GRAY_STAINED_GLASS", 4102);
		LIGHT_GRAY_STAINED_GLASS = c("LIGHT_GRAY_STAINED_GLASS", 4103);
		CYAN_STAINED_GLASS = c("CYAN_STAINED_GLASS", 4104);
		PURPLE_STAINED_GLASS = c("PURPLE_STAINED_GLASS", 4105);
		BLUE_STAINED_GLASS = c("BLUE_STAINED_GLASS", 4106);
		BROWN_STAINED_GLASS = c("BROWN_STAINED_GLASS", 4107);
		GREEN_STAINED_GLASS = c("GREEN_STAINED_GLASS", 4108);
		RED_STAINED_GLASS = c("RED_STAINED_GLASS", 4109);
		BLACK_STAINED_GLASS = c("BLACK_STAINED_GLASS", 4110);
		WHITE_STAINED_GLASS_PANE,
		ORANGE_STAINED_GLASS_PANE,
		MAGENTA_STAINED_GLASS_PANE,
		LIGHT_BLUE_STAINED_GLASS_PANE,
		YELLOW_STAINED_GLASS_PANE,
		LIME_STAINED_GLASS_PANE,
		PINK_STAINED_GLASS_PANE,
		GRAY_STAINED_GLASS_PANE,
		LIGHT_GRAY_STAINED_GLASS_PANE,
		CYAN_STAINED_GLASS_PANE,
		PURPLE_STAINED_GLASS_PANE,
		BLUE_STAINED_GLASS_PANE,
		BROWN_STAINED_GLASS_PANE,
		GREEN_STAINED_GLASS_PANE,
		RED_STAINED_GLASS_PANE,
		BLACK_STAINED_GLASS_PANE,
		PRISMARINE,
		PRISMARINE_BRICKS,
		DARK_PRISMARINE,
		PRISMARINE_STAIRS,
		PRISMARINE_BRICK_STAIRS,
		DARK_PRISMARINE_STAIRS,
		SEA_LANTERN,
		RED_SANDSTONE,
		CHISELLED_RED_SANDSTONE,
		CUT_RED_SANDSTONE,
		RED_SANDSTONE_STAIRS,
		REPEATING_COMMAND_BLOCK,
		CHAIN_COMMAND_BLOCK,
		MAGMA_BLOCK,
		NETHER_WART_BLOCK,
		WARPED_WART_BLOCK,
		RED_NETHER_BRICKS,
		BONE_BLOCK,
		STRUCTURE_VOID,
		OBSERVER,
		SHULKER_BOX,
		WHITE_SHULKER_BOX,
		ORANGE_SHULKER_BOX,
		MAGENTA_SHULKER_BOX,
		LIGHT_BLUE_SHULKER_BOX,
		YELLOW_SHULKER_BOX,
		LIME_SHULKER_BOX,
		PINK_SHULKER_BOX,
		GRAY_SHULKER_BOX,
		LIGHT_GRAY_SHULKER_BOX,
		CYAN_SHULKER_BOX,
		PURPLE_SHULKER_BOX,
		BLUE_SHULKER_BOX,
		BROWN_SHULKER_BOX,
		GREEN_SHULKER_BOX,
		RED_SHULKER_BOX,
		BLACK_SHULKER_BOX,
		WHITE_GLAZED_TERRACOTTA,
		ORANGE_GLAZED_TERRACOTTA,
		MAGENTA_GLAZED_TERRACOTTA,
		LIGHT_BLUE_GLAZED_TERRACOTTA,
		YELLOW_GLAZED_TERRACOTTA,
		LIME_GLAZED_TERRACOTTA,
		PINK_GLAZED_TERRACOTTA,
		GRAY_GLAZED_TERRACOTTA,
		LIGHT_GRAY_GLAZED_TERRACOTTA,
		CYAN_GLAZED_TERRACOTTA,
		PURPLE_GLAZED_TERRACOTTA,
		BLUE_GLAZED_TERRACOTTA,
		BROWN_GLAZED_TERRACOTTA,
		GREEN_GLAZED_TERRACOTTA,
		RED_GLAZED_TERRACOTTA,
		BLACK_GLAZED_TERRACOTTA,
		WHITE_CONCRETE,
		ORANGE_CONCRETE,
		MAGENTA_CONCRETE,
		LIGHT_BLUE_CONCRETE,
		YELLOW_CONCRETE,
		LIME_CONCRETE,
		PINK_CONCRETE,
		GRAY_CONCRETE,
		LIGHT_GRAY_CONCRETE,
		CYAN_CONCRETE,
		PURPLE_CONCRETE,
		BLUE_CONCRETE,
		BROWN_CONCRETE,
		GREEN_CONCRETE,
		RED_CONCRETE,
		BLACK_CONCRETE,
		WHITE_CONCRETE_POWDER,
		ORANGE_CONCRETE_POWDER,
		MAGENTA_CONCRETE_POWDER,
		LIGHT_BLUE_CONCRETE_POWDER,
		YELLOW_CONCRETE_POWDER,
		LIME_CONCRETE_POWDER,
		PINK_CONCRETE_POWDER,
		GRAY_CONCRETE_POWDER,
		LIGHT_GRAY_CONCRETE_POWDER,
		CYAN_CONCRETE_POWDER,
		PURPLE_CONCRETE_POWDER,
		BLUE_CONCRETE_POWDER,
		BROWN_CONCRETE_POWDER,
		GREEN_CONCRETE_POWDER,
		RED_CONCRETE_POWDER,
		BLACK_CONCRETE_POWDER,
		TURTLE_EGG,
		DEAD_TUBE_CORAL_BLOCK,
		DEAD_BRAIN_CORAL_BLOCK,
		DEAD_BUBBLE_CORAL_BLOCK,
		DEAD_FIRE_CORAL_BLOCK,
		DEAD_HORN_CORAL_BLOCK,
		TUBE_CORAL_BLOCK,
		BRAIN_CORAL_BLOCK,
		BUBBLE_CORAL_BLOCK,
		FIRE_CORAL_BLOCK,
		HORN_CORAL_BLOCK,
		TUBE_CORAL,
		BRAIN_CORAL,
		BUBBLE_CORAL,
		FIRE_CORAL,
		HORN_CORAL,
		DEAD_BRAIN_CORAL,
		DEAD_BUBBLE_CORAL,
		DEAD_FIRE_CORAL,
		DEAD_HORN_CORAL,
		DEAD_TUBE_CORAL,
		TUBE_CORAL_FAN,
		BRAIN_CORAL_FAN,
		BUBBLE_CORAL_FAN,
		FIRE_CORAL_FAN,
		HORN_CORAL_FAN,
		DEAD_TUBE_CORAL_FAN,
		DEAD_BRAIN_CORAL_FAN,
		DEAD_BUBBLE_CORAL_FAN,
		DEAD_FIRE_CORAL_FAN,
		DEAD_HORN_CORAL_FAN,
		BLUE_ICE,
		CONDUIT,
		POLISHED_GRANITE_STAIRS,
		SMOOTH_RED_SANDSTONE_STAIRS,
		MOSSY_STONE_BRICK_STAIRS,
		POLISHED_DIORITE_STAIRS,
		MOSSY_COBBLESTONE_STAIRS,
		END_STONE_BRICK_STAIRS,
		STONE_STAIRS,
		SMOOTH_SANDSTONE_STAIRS,
		SMOOTH_QUARTZ_STAIRS,
		GRANITE_STAIRS,
		ANDESITE_STAIRS,
		RED_NETHER_BRICK_STAIRS,
		POLISHED_ANDESITE_STAIRS,
		DIORITE_STAIRS,
		POLISHED_GRANITE_SLAB,
		SMOOTH_RED_SANDSTONE_SLAB,
		MOSSY_STONE_BRICK_SLAB,
		POLISHED_DIORITE_SLAB,
		MOSSY_COBBLESTONE_SLAB,
		END_STONE_BRICK_SLAB,
		SMOOTH_SANDSTONE_SLAB,
		SMOOTH_QUARTZ_SLAB,
		GRANITE_SLAB,
		ANDESITE_SLAB,
		RED_NETHER_BRICK_SLAB,
		POLISHED_ANDESITE_SLAB,
		DIORITE_SLAB,
		SCAFFOLDING,
		IRON_DOOR = c("IRON_DOOR", 3809, DOOR_MDF);
		OAK_DOOR = c("OAK_DOOR", 3573, DOOR_MDF);
		SPRUCE_DOOR,
		BIRCH_DOOR,
		JUNGLE_DOOR,
		ACACIA_DOOR,
		DARK_OAK_DOOR,
		CRIMSON_DOOR,
		WARPED_DOOR,
		REPEATER = c("REPEATER", 4031, REPEATER_MDF);
		COMPARATOR = c("COMPARATOR", 6682, COMPARATOR_MDF);
		STRUCTURE_BLOCK,
		JIGSAW,
		TURTLE_HELMET,
		SCUTE,
		FLINT_AND_STEEL,
		APPLE,
		ARROW,
		COAL,
		CHARCOAL,
		DIAMOND,
		IRON_INGOT,
		GOLD_INGOT,
		NETHERITE_INGOT,
		NETHERITE_SCRAP,
		WOODEN_SWORD,
		WOODEN_SHOVEL,
		WOODEN_PICKAXE,
		WOODEN_AXE,
		WOODEN_HOE,
		STONE_SWORD,
		STONE_SHOVEL,
		STONE_PICKAXE,
		STONE_AXE,
		STONE_HOE,
		GOLDEN_SWORD,
		GOLDEN_SHOVEL,
		GOLDEN_PICKAXE,
		GOLDEN_AXE,
		GOLDEN_HOE,
		IRON_SWORD,
		IRON_SHOVEL,
		IRON_PIKAXE,
		IRON_AXE,
		IRON_HOE,
		DIAMOND_SWORD,
		DIAMOND_SHOVEL,
		DIAMOND_PICKAXE,
		DIAMOND_AXE,
		DIAMOND_HOE,
		NETHERITE_SWORD,
		NETHERITE_SHOVEL,
		NETHERITE_PICKAXE,
		NETHERITE_AXE,
		NETHERITE_HOE,
		STICK,
		BOWL,
		MUSHROOM_STEW,
		STRING,
		FEATHER,
		GUN_POWDER,
		WHEAT_SEEDS,
		WHEAT = c("WHEAT", 3357, AGEABLE_MDF);
		BREAD,
		LEATHER_HELMET,
		LEATHER_CHESTPLATE,
		LEATHER_LEGGINGS,
		LEATHER_BOOTS,
		CHAINMAIL_HELMET,
		CHAINMAIL_CHESTPLATE,
		CHAINMAIL_LEGGINGS,
		CHAINMAIL_BOOTS,
		IRON_HELMET,
		IRON_CHESTPLATE,
		IRON_LEGGINGS,
		IRON_BOOTS,
		DIAMOND_HELMET,
		DIAMOND_CHESTPLATE,
		DIAMOND_LEGGINGS,
		DIAMOND_BOOTS,
		GOLDEN_HELMET,
		GOLDEN_CHESTPLATE,
		GOLDEN_LEGGINGS,
		GOLDEN_BOOTS,
		NETHERITE_HELMET,
		NETHERITE_CHESTPLATE,
		NETHERITE_LEGGINGS,
		NETHERITE_BOOTS,
		FLINT,
		PORKCHOP,
		COOKED_PORKCHOP,
		PAINTING,
		GOLDEN_APPLE,
		ENCHANTED_GOLDEN_APPLE,
		OAK_SIGN = c("OAK_SIGN", 3381, SIGN_MDF);
		SPRUCE_SIGN = c("SPRUCE_SIGN", 3413, SIGN_MDF);
		BIRCH_SIGN = c("BIRCH_SIGN", 3445, SIGN_MDF);
		JUNGLE_SIGN = c("JUNGLE_SIGN", 3509, SIGN_MDF);
		ACACIA_SIGN = c("ACACIA_SIGN", 3477, SIGN_MDF);
		DARK_OAK_SIGN = c("DARK_OAK_SIGN", 3541, SIGN_MDF);
		CRIMSON_SIGN,
		WARPED_SIGN,
		OAK_WALL_SIGN = new Material("OAK_WALL_SIGN", false, (short) 3735, WALL_SIGN_MDF);
		SPRUCE_WALL_SIGN = new Material("SPRUCE_WALL_SIGN", false, (short) 3743, WALL_SIGN_MDF);
		BIRCH_WALL_SIGN = new Material("BIRCH_WALL_SIGN", false, (short) 3751, WALL_SIGN_MDF);
		JUNGLE_WALL_SIGN = new Material("JUNGLE_WALL_SIGN", false, (short) 3759, WALL_SIGN_MDF);
		ACACIA_WALL_SIGN = new Material("ACACIA_WALL_SIGN", false, (short) 3767, WALL_SIGN_MDF);
		DARK_OAK_WALL_SIGN = new Material("DARK_OAK_WALL_SIGN", false, (short) 3775, WALL_SIGN_MDF);
		CRIMSON_WALL_SIGN,
		WARPED_WALL_SIGN,
		BUCKET,
		WATER_BUCKET,
		LAVA_BUCKET,
		MINECART,
		SADDLE,
		REDSTONE,
		SNOWBALL,
		OAK_BOAT,
		LEATHER,
		MILK_BUCKET,
		PUFFERFISH_BUCKET,
		SALMON_BUCKET,
		COD_BUCKET,
		TROPICAL_FISH_BUCKET,
		BRICK,
		CLAY_BALL,
		DRIED_KELP_BLOCK,
		PAPER,
		BOOK,
		SLIME_BALL,
		CHEST_MINECART,
		FURNACE_MINECART,
		EGG,
		COMPASS,
		FISHING_ROD,
		CLOCK,
		GLOWSTONE_DUST,
		COD,
		SALMON,
		TROPICAL_FISH,
		PUFFERFISH,
		COOKED_COD,
		COOKED_SALMON,
		INK_SAC,
		COCOA_BEANS,
		LAPIS_LAZULI,
		WHITE_DYE,
		ORANGE_DYE,
		MAGENTA_DYE,
		LIGHT_BLUE_DYE,
		YELLOW_DYE,
		LIME_DYE,
		PINK_DYE,
		GRAY_DYE,
		LIGHT_GRAY_DYE,
		CYAN_DYE,
		PURPLE_DYE,
		BLUE_DYE,
		BROWN_DYE,
		GREEN_DYE,
		RED_DYE,
		BLACK_DYE,
		BONE_MEAL,
		BONE,
		SUGAR,
		CAKE = c("CAKE", 4024, CAKE_MDF);
		WHITE_BED = c("WHITE_BED", 1049, BED_MDF);
		ORANGE_BED = c("ORANGE_BED", 1065, BED_MDF);
		MAGENTA_BED = c("MAGENTA_BED", 1081, BED_MDF);
		LIGHT_BLUE_BED = c("LIGHT_BLUE_BED", 1097, BED_MDF);
		YELLOW_BED = c("YELLOW_BED", 1113, BED_MDF);
		LIME_BED = c("LIME_BED", 1129, BED_MDF);
		PINK_BED = c("PINK_BED", 1145, BED_MDF);
		GRAY_BED = c("GRAY_BED", 1161, BED_MDF);
		LIGHT_GRAY_BED = c("LIGHT_GRAY_BED", 1177, BED_MDF);
		CYAN_BED = c("CYAN_BED", 1193, BED_MDF);
		PURPLE_BED = c("PURPLE_BED", 1209, BED_MDF);
		BLUE_BED = c("BLUE_BED", 1225, BED_MDF);
		BROWN_BED = c("BROWN_BED", 1241, BED_MDF);
		GREEN_BED = c("GREEN_BED", 1257, BED_MDF);
		RED_BED = c("RED_BED", 1273, BED_MDF);
		BLACK_BED = c("BLACK_BED", 1289, BED_MDF);
		COOKIE,
		FILLED_MAP,
		SHEARS,
		MELON_SLICE,
		DRIED_KELP,
		PUMPKIN_SEED,
		MELON_SEEDS,
		BEEF,
		COOKED_BEEF,
		CHICKEN,
		COOKED_CHICKEN,
		ROTTEN_FLESH,
		ENDER_PEARL,
		BLAZE_ROD,
		GHAST_TEAR,
		GOLD_NUGGET,
		NETHER_WART = c("NETHER_WART", 5132, AGEABLE_MDF);
		POTION,
		GLASS_BOTTLE,
		SPIDER_EYE,
		FERMENTED_SPIDER_EYE,
		BLAZE_POWDER,
		MAGMA_CREAM,
		BREWING_STAND = c("BREWING_STAND", 5137, BREWING_STAND_MDF);
		CAULDRON = c("CAULDRON", 5146, LEVELLED_MDF);
		ENDER_EYE,
		GLISTERING_MELON_SLICE,
		BAT_SPAWN_EGG,
		BEE_SPAWN_EGG,
		BLAZE_SPAWN_EGG,
		CAT_SPAWN_EGG,
		CAVE_SPIDER_SPAWN_EGG,
		CHICKEN_SPAWN_EGG,
		COD_SPAWN_EGG,
		COW_SAWN_EGG,
		CREEPER_SPAWN_EGG,
		DOLPHIN_SPAWN_EGG,
		DONKEY_SPAWN_EGG,
		DROWNED_SPAWN_EGG,
		ELDER_GUARDIAN_SPAWN_EGG,
		ENDERMAN_SPAWN_EGG,
		ENDERMITE_SPAWN_EGG,
		EVOKER_SPAWN_EGG,
		FOX_SPAWN_EGG,
		GHAST_SPAWN_EGG,
		GUARDIAN_SPAWN_EGG,
		HOGLIN_SPAWN_EGG,
		HORSE_SPAWN_EGG,
		HUSK_SPAWN_EGG,
		LLAMA_SPAWN_EGG,
		MAGMA_CUBE_SPAWN_EGG,
		MOOSHROOM_SPAWN_EGG,
		MULE_SPAWN_EGG,
		OCELOT_SPAWN_EGG,
		PANDA_SPAWN_EGG,
		PARROT_SPAWN_EGG,
		PHANTOM_SPAWN_EGG,
		PIG_SPAWN_EGG,
		PIGLIN_SPAWN_EGG,
		PIGLIN_BRUTE_SPAWN_EGG,
		PILLAGER_SPAWN_EGG,
		POLAR_BEAR_SPAWN_EGG,
		PUFFERFISH_SPAWN_EGG,
		RABBIT_SPAWN_EGG,
		RAVAGER_SPAWN_EGG,
		SALMON_SPAWN_EGG,
		SHEEP_SPAWN_EGG,
		SHULKER_SPAWN_EGG,
		SILVERFISH_SPAWN_EGG,
		SKELETON_SPAWN_EGG,
		SKELETON_HORSE_SPAWN_EGG,
		SLIME_SPAWN_EGG,
		SPIDER_SPAWN_EGG,
		SQUID_SPAWN_EGG,
		STRAY_SPAWN_EGG,
		STRIDER_SPAWN_EGG,
		TRADER_LLAMA_SPAWN_EGG,
		TROPICAL_FISH_SPAWN_EGG,
		TURTLE_SPAWN_EGG,
		VEX_SPAWN_EGG,
		VILLAGER_SPAWN_EGG,
		VINDICATOR_SPAWN_EGG,
		WANDERING_TRADER_SPAWN_EGG,
		WITCH_SPAWN_EGG,
		WITHER_SKELETON_SPAWN_EGG,
		WOLF_SPAWN_EGG,
		ZOGLIN_SPAWN_EGG,
		ZOMBIE_SPAWN_EGG,
		ZOMBIE_VILLAGER_SPAWN_EGG,
		ZOMBIEFIED_PIG_SPAWN_EGG,
		EXPERIENCE_BOTTLE,
		FIRE_CHARGE,
		WRITEABLE_BOOK,
		WRITTEN_BOOK,
		EMERALD,
		ITEM_FRAME,
		FLOWER_POT = c("FLOWER_POT", 6309);
		POTTET_OAK_SAPLING = new Material("POTTET_OAK_SAPLING", false, (short) 6310);
		POTTET_SPRUCE_SAPLING = new Material("POTTET_SPRUCE_SAPLING", false, (short) 6311);
		POTTET_BIRCH_SAPLING = new Material("POTTET_BIRCH_SAPLING", false, (short) 6312);
		POTTET_JUNGLE_SAPLING = new Material("POTTET_JUNGLE_SAPLING", false, (short) 6313);
		POTTET_ACACIA_SAPLING = new Material("POTTET_ACACIA_SAPLING", false, (short) 6314);
		POTTET_DARK_OAK_SAPLING = new Material("POTTET_DARK_OAK_SAPLING", false, (short) 6315);
		POTTET_FERN = new Material("POTTET_DARK_OAK_SAPLING", false, (short) 6316);
		POTTET_DANDELION = new Material("POTTET_DANDELION", false, (short) 6317);
		POTTET_POPPY = new Material("POTTET_POPPY", false, (short) 6318);
		POTTET_BLUE_ORCHID = new Material("POTTET_BLUE_ORCHID", false, (short) 6319);
		POTTET_ALLIUM = new Material("POTTET_ALLIUM", false, (short) 6320);
		POTTET_AZURE_BLUET = new Material("POTTET_AZURE_BLUET", false, (short) 6321);
		POTTET_RED_TULIP = new Material("POTTET_RED_TULIP", false, (short) 6322);
		POTTET_ORANGE_TULIP = new Material("POTTET_ORANGE_TULIP", false, (short) 6323);
		POTTET_WHITE_TULIP = new Material("POTTET_WHITE_TULIP", false, (short) 6324);
		POTTET_PINK_TULIP = new Material("POTTET_PINK_TULIP", false, (short) 6325);
		POTTET_OXEYE_DAISY = new Material("POTTET_OXEYE_DAISY", false, (short) 6326);
		POTTET_CORNFLOWER = new Material("POTTET_CORNFLOWER", false, (short) 6327);
		POTTET_LILY_OF_THE_VALLEY = new Material("POTTET_LILY_OF_THE_VALLEY", false, (short) 6328);
		POTTET_WITHER_ROSE = new Material("POTTET_WITHER_ROSE", false, (short) 6329);
		POTTET_RED_MUSHROOM = new Material("POTTET_RED_MUSHROOM", false, (short) 6330);
		POTTET_BROWN_MUSHROOM = new Material("POTTET_BROWN_MUSHROOM", false, (short) 6331);
		POTTET_DEAD_BUSH = new Material("POTTET_DEAD_BUSH", false, (short) 6332);
		POTTET_CACTUS = new Material("POTTET_CACTUS", false, (short) 6333);
		CARROT,
		CARROTS = new Material("CARROTS", false, (short) 6334, AGEABLE_MDF);
		POTATO,
		POTATOES = new Material("POTATOES", false, (short) 6342, AGEABLE_MDF);
		BAKED_POTATO,
		POISONOUS_POTATO,
		MAP,
		GOLDEN_CARROT,
		SKELETON_SKULL = c("SKELETON_SKULL", 6494, ROTATABLE_MDF);
		SKELETON_WALL_SKULL = new Material("SKELETON_WALL_SKULL", false, (short) 6510, DIRECTIONAL_MDF);
		WITHER_SKELETON_SKULL = c("WITHER_SKELETON_SKULL", 6514, ROTATABLE_MDF);
		WITHER_SKELETON_WALL_SKULL = new Material("WITHER_SKELETON_WALL_SKULL", false, (short) 6530, DIRECTIONAL_MDF);
		PLAYER_HEAD = c("PLAYER_HEAD", 6554, ROTATABLE_MDF);
		PLAYER_WALL_HEAD = new Material("PLAYER_WALL_HEAD", false, (short) 6570, DIRECTIONAL_MDF);
		ZOMBIE_HEAD = c("ZOMBIE_HEAD", 6534, ROTATABLE_MDF);
		ZOMBIE_WALL_HEAD = new Material("ZOMBIE_WALL_HEAD", false, (short) 6550, DIRECTIONAL_MDF);
		CREEPER_HEAD = c("CREEPER_HEAD", 6574, ROTATABLE_MDF);
		CREEPER_WALL_HEAD = new Material("CREEPER_WALL_HEAD", false, (short) 6590, DIRECTIONAL_MDF);
		DRAGON_HEAD = c("DRAGON_HEAD", 6594, ROTATABLE_MDF);
		DRAGON_WALL_HEAD = new Material("DRAGON_WALL_HEAD", false, (short) 6610, DIRECTIONAL_MDF);
		CARROT_ON_A_STICK,
		WARPED_FUNGUS_ON_A_STICK,
		NETHER_STAR,
		PUMPKIN_PIE,
		FIREWORK_ROCKET,
		FIREWORK_STAR,
		ENCHANTED_BOOK,
		NETHER_BRICK,
		QUARTZ,
		TNT_MINECART,
		HOPPER_MINECART,
		PRISMARINE_SHARD,
		PRISMARINE_CRYSTALS,
		RABBIT,
		COOKED_RABBIT,
		RABBIT_STEW,
		RABBIT_FOOT,
		RABBIT_HIDE,
		ARMOR_STAND,
		IRON_HORSE_ARMOR,
		GOLDEN_HORSE_ARMOR,
		DIAMOND_HORSE_ARMOR,
		LEAD,
		NAME_TAG,
		COMMAND_BLOCK_MINECART,
		MUTTON,
		COOKED_MUTTON,
		WHITE_BANNER,
		ORANGE_BANNER,
		MAGENTA_BANNER,
		LIGHT_BLUE_BANNER,
		YELLOW_BANNER,
		LIME_BANNER,
		PINK_BANNER,
		GRAY_BANNER,
		LIGHT_GRAY_BANNER,
		CYAN_BANNER,
		PURPLE_BANNER,
		BLUE_BANNER,
		BROWN_BANNER,
		GREEN_BANNER,
		RED_BANNER,
		BLACK_BANNER,
		END_CRYSTAL,
		CHORUS_FRUIT,
		POPPED_CHORUS_FRUIT,
		BEETROOT,
		BEETROOT_SOUP,
		DRAGON_BREATH,
		SPLASH_POTION,
		SPECTRAL_ARROW,
		TIPPED_ARROW,
		LINGERING_POTION,
		SHIELD,
		ELYTRA,
		SPRUCE_BOAT,
		BIRCH_BOAT,
		JUNGLE_BOAT,
		ACACIA_BOAT,
		DARK_OAK_BOAT,
		TOTEM_OF_UNDYING,
		SHULKER_SHELL,
		IRON_NUGGET,
		KNOWLEDGE_BOOK,
		DEBUG_STICK,
		MUSIC_DISC_13,
		MUSIC_DISC_CAT,
		MUSIC_DISC_BLOCKS,
		MUSIC_DISC_CHIRP,
		MUSIC_DISC_FAR,
		MUSIC_DISC_MALL,
		MUSIC_DISC_STAL,
		MUSIC_DISC_STRAD,
		MUSIC_DISC_WARD,
		MUSIC_DISC_11,
		MUSIC_DISC_WAIT,
		MUSIC_DISC_PIGSTEP,
		TRIDENT,
		PHANTOM_MEMBRANE,
		NAUTILUS_SHELL,
		HEART_OF_THE_SEA,
		CROSSBOW,
		SUSPICIOUS_STEW,
		LOOM,
		FLOWER_BANNER_PATTERN,
		CREEPER_BANNER_PATTERN,
		SKULL_BANNER_PATTERN,
		MOJANG_BANNER_PATTERN,
		GLOBE_BANNER_PATTERN,
		PIGLIN_BANNER_PATTERN,
		COMPOSTER,
		BARREL,
		SMOKER,
		BlAST_FURNACE,
		CARTOGRAPHY_TABLE,
		FLETCHING_TABLE,
		GRINDSTONE,
		LECTERN,
		SMITHING_TABLE,
		STONECUTTER,
		BELL,
		LANTERN,
		SOUL_LANTERN,
		SWEET_BERRIES,
		CAMPFIRE,
		SOUL_CAMPFIRE,
		SHROOMLIGHT,
		HONEYCOMB,
		BEE_NEST,
		BEEHIVE,
		HONEY_BOTTLE,
		HONEY_BLOCK,
		HONEYCOMB_BLOCK,
		LODESTONE,
		NETHERITE_BLOCK,
		ANCIENT_DEBRIS,
		TARGET,
		CRYING_OBSIDIAN,
		BLACKSTONE,
		BLACKSTONE_SLAB,
		BLACKSTONE_STAIRS,
		GILDED_BLACKSTONE,
		POLISHED_BLACKSTONE,
		POLISHED_BLACKSTONE_SLAB,
		POLISHED_BLACKSTONE_STAIRS,
		CHISELED_POLISHED_BLACKSTONE,
		POLISHED_BLACKSTONE_BRICKS,
		POLISHED_BLACKSTONE_BRICK_SLAB,
		POLISHED_BLACKSTONE_BRICK_STAIRS,
		CRACKED_POLISHED_BLACKSTONE_BRICKS,
		RESPAWN_ANCHOR;
	}
	
	private static Material c(String name, int blockID) {
		new Material(name, (short) blockID, null);
	}
	
	private static Material c(String name, int blockID, MetaDataFactory mdf) {
		new Material(name, (short) blockID, mdf);
	}
	
	private final String name;
	private final short itemID, bid;
	
	/**
	 * 
	 * @param name the Material's name
	 * @param itemID the protocol ItemID or -1 if it has no Item
	 * @param blockID the protocol BlockID or -1 if it has no Block
	 * @param mdf null to use MetaDataFactory.DEFAULT
	 */
	public Material(String name, short itemID, short blockID,  MetaDataFactory mdf) {
		if (name == null) throw new IllegalArgumentException("Name can not be null!");
		this.name = name;
		this.itemID = itemID;
		this.bid = blockID;
		registerMaterial();
		setMetaDataFactory(this, mdf);
	}
	
	public Material(String name, MetaDataFactory mdf) {
		this(name, true, (short) -1, mdf);
	}
	
	public Material(String name, boolean hasItem, short blockID) {
		this(name, hasItem, blockID, null);
	}
	
	public Material(String name, boolean hasItem, short blockID, MetaDataFactory mdf) {
		if (name == null) throw new IllegalArgumentException("Name can not be null!");
		this.name = name;
		this.itemID = hasItem ? iid++ : -1;
		registerMaterial();
		setMetaDataFactory(this, mdf);
	}
	
	public Material(String name, short blockID,  MetaDataFactory mdf) {
		this(name, true, blockID,  mdf);
	}
	
	public String name() {
		return name.toUpperCase();
	}
	
	public short getItemID() {
		return itemID;
	}
	
	public short getBlockID() {
		return bid;
	}
	
	public MetaDataFactory getMetaDataFactory() {
		return META_FACTORYS.get(this);
	}
	
	public void setMetaDataFactory(Material material, MetaDataFactory factory) {
		if (factory == null) META_FACTORYS.remove(material);
		else META_FACTORYS.put(material, factory);
	}
	
	public ItemMeta createItemMeta() {
		MetaDataFactory mdf = getMetaDataFactory();
		if (mdf == null) return MetaDataFactory.DEFAULT.createMeta(this);
		return mdf.createMeta(this);
	}
	
	public BlockData createBlockData() {
		MetaDataFactory mdf = getMetaDataFactory();
		if (mdf == null) return MetaDataFactory.DEFAULT.createData(this);
		return mdf.createData(this);
	}
	
	public boolean isItem() {
		return itemID != -1;
	}
	
	public boolean isBlock() {
		return bid != -1;
	}
	
	public static List<Material> values() {
		return new ArrayList<Material>(BY_NAME.values());
	}
	
	protected final void registerMaterial() {
		if (BY_NAME.containsValue(this)) throw new Error("Material already registered");
		if (BY_NAME.containsKey(this.name())) throw new Error("Material with this name already registered");
		BY_NAME.put(this.name(), this);
	}
	
	public final void unregister() {
		BY_NAME.remove(this.name());
		META_FACTORYS.remove(this);
	}

	public boolean isValidMeta(ItemMeta meta) {
		if (meta.getType() != this) return false;
		MetaDataFactory mdf = getMetaDataFactory();
		if (mdf == null) return MetaDataFactory.DEFAULT.isValidMeta(meta);
		return mdf.isValidMeta(meta);
	}
	
	public boolean isValidData(BlockData data) {
		if (data.getType() != this) return false;
		MetaDataFactory mdf = getMetaDataFactory();
		if (mdf == null) return MetaDataFactory.DEFAULT.isValidData(data);
		return mdf.isValidData(data);
	}
	
}
