defaults:
  console-layout: '%d{MM-dd HH:mm:ss} %p\t| %al - %m%n'
  file-layout: '%d{yyyy-MM-dd HH:mm:ss} %p\t| %al - %m%n'
groups:
  Atlas-Master: # System internal pleae keep this name
    level: debug
    file:
      file-name: master/latest.log
      file-pattern: master/log_%d{yyyy-MM-dd}.log
  Atlas: # System internal please keep this name
    level: debug
    file:
      file-name: latest.log
      file-pattern: log_%d{yyyy-MM-dd}.log
  Proxy: # System internal please keep this name
    level: debug
    file:
      file-name: proxy/latest.log
      file-pattern: proxy/log_%d{yyyy-MM-dd}.log
  Server: # System internal please keep this name
    level: debug
    file:
      file-name: server/latest.log
      file-pattern: server/log_%d{yyyy-MM-dd}.log
  Plugin: # System internal please keep this name
    level: debug
    file:
      file-name: plugin/latest.log
      file-pattern: plugin/log_%d{yyyy-MM-dd}.log
      layout: '%d{yyyy-MM-dd HH:mm:ss} %p\t| Plugin [%al] - %m%n'
    console:
      layout: '%d{MM-dd HH:mm:ss} %p\t| Plugin [%al] - %m%n'